package beachc.ast

package object graphs {
  val TTTBoard = 
    Graph(
      List(
        Point((0, 0)), Point((1, 0)), Point((2, 0)), 
        Point((0, 1)), Point((1, 1)), Point((2, 1)), 
        Point((0, 2)), Point((1, 2)), Point((2, 2))
      ),
      List(
        CardinalEdge(Point((0, 0)), Point((0, 1)), East),
        CardinalEdge(Point((0, 0)), Point((1, 0)), South), 
        CardinalEdge(Point((0, 0)), Point((1, 1)), SouthEast),

        CardinalEdge(Point((0, 1)), Point((0, 0)), West),
        CardinalEdge(Point((0, 1)), Point((0, 2)), East),
        CardinalEdge(Point((0, 1)), Point((1, 0)), SouthWest),
        CardinalEdge(Point((0, 1)), Point((1, 1)), South),
        CardinalEdge(Point((0, 1)), Point((1, 2)), SouthEast),

        CardinalEdge(Point((0, 2)), Point((0, 1)), West), 
        CardinalEdge(Point((0, 2)), Point((1, 1)), SouthWest), 
        CardinalEdge(Point((0, 2)), Point((1, 2)), South), 

        CardinalEdge(Point((1, 0)), Point((0, 0)), North),
        CardinalEdge(Point((1, 0)), Point((0, 1)), NorthEast),
        CardinalEdge(Point((1, 0)), Point((1, 1)), East),
        CardinalEdge(Point((1, 0)), Point((2, 0)), South),
        CardinalEdge(Point((1, 0)), Point((2, 1)), SouthEast),

        CardinalEdge(Point((1, 1)), Point((0, 0)), NorthWest),
        CardinalEdge(Point((1, 1)), Point((0, 1)), North),
        CardinalEdge(Point((1, 1)), Point((0, 2)), NorthEast),
        CardinalEdge(Point((1, 1)), Point((1, 0)), West),
        CardinalEdge(Point((1, 1)), Point((1, 2)), East),
        CardinalEdge(Point((1, 1)), Point((2, 0)), SouthWest),
        CardinalEdge(Point((1, 1)), Point((2, 1)), South),
        CardinalEdge(Point((1, 1)), Point((2, 2)), SouthEast),

        CardinalEdge(Point((1, 2)), Point((0, 1)), NorthWest),
        CardinalEdge(Point((1, 2)), Point((0, 2)), North),
        CardinalEdge(Point((1, 2)), Point((1, 1)), West),
        CardinalEdge(Point((1, 2)), Point((2, 1)), SouthWest),
        CardinalEdge(Point((1, 2)), Point((2, 2)), South),

        CardinalEdge(Point((2, 0)), Point((1, 0)), North),
        CardinalEdge(Point((2, 0)), Point((1, 1)), NorthEast),
        CardinalEdge(Point((2, 0)), Point((2, 1)), East),

        CardinalEdge(Point((2, 1)), Point((1, 0)), NorthWest),
        CardinalEdge(Point((2, 1)), Point((1, 1)), North),
        CardinalEdge(Point((2, 1)), Point((1, 2)), NorthEast),
        CardinalEdge(Point((2, 1)), Point((2, 0)), West), 
        CardinalEdge(Point((2, 1)), Point((2, 2)), East),

        CardinalEdge(Point((2, 2)), Point((1, 1)), NorthWest),
        CardinalEdge(Point((2, 2)), Point((1, 2)), North),
        CardinalEdge(Point((2, 2)), Point((2, 1)), West)
      )
    )

  val ChessBoard =
    Graph(
      List(
        Point((0, 0)), Point((1, 0)), Point((2, 0)), Point(3, 0), Point(4, 0), Point((5, 0)), Point((6, 0)), Point((7, 0)),
        Point((0, 1)), Point((1, 1)), Point((2, 1)), Point(3, 1), Point(4, 1), Point((5, 1)), Point((6, 1)), Point((7, 1)),
        Point((0, 2)), Point((1, 2)), Point((2, 2)), Point(3, 2), Point(4, 2), Point((5, 2)), Point((6, 2)), Point((7, 2)),
        Point((0, 3)), Point((1, 3)), Point((2, 3)), Point(3, 3), Point(4, 3), Point((5, 3)), Point((6, 3)), Point((7, 3)),
        Point((0, 4)), Point((1, 4)), Point((2, 4)), Point(3, 4), Point(4, 4), Point((5, 4)), Point((6, 4)), Point((7, 4)),
        Point((0, 5)), Point((1, 5)), Point((2, 5)), Point(3, 5), Point(4, 5), Point((5, 5)), Point((6, 5)), Point((7, 5)),
        Point((0, 6)), Point((1, 6)), Point((2, 6)), Point(3, 6), Point(4, 6), Point((5, 6)), Point((6, 6)), Point((7, 6)),
        Point((0, 8)), Point((1, 8)), Point((2, 8)), Point(3, 8), Point(4, 8), Point((5, 8)), Point((6, 8)), Point((7, 8))
      ),
      List(
        // Northwest corner
        CardinalEdge(Point((0, 0)), Point((0, 1)), East),
        CardinalEdge(Point((0, 0)), Point((1, 0)), South),
        CardinalEdge(Point((0, 0)), Point((1, 1)), SouthEast),
        
        // Northeast corner
        CardinalEdge(Point((0, 7)), Point((0, 6)), West),
        CardinalEdge(Point((0, 7)), Point((1, 6)), SouthWest),
        CardinalEdge(Point((0, 7)), Point((1, 7)), South),
        

        // Southwest corner
        CardinalEdge(Point((7, 0)), Point((6, 0)), North),
        CardinalEdge(Point((7, 0)), Point((6, 1)), NorthEast),
        CardinalEdge(Point((7, 0)), Point((7, 1)), East),

        // Southeast corner
        CardinalEdge(Point((7, 7)), Point((6, 6)), NorthWest),
        CardinalEdge(Point((7, 7)), Point((6, 7)), North),
        CardinalEdge(Point((7, 7)), Point((7, 6)), West),

        // North Edge
        CardinalEdge(Point((0, 1)), Point((0, 0)), West),
        CardinalEdge(Point((0, 1)), Point((0, 2)), East),
        CardinalEdge(Point((0, 1)), Point((1, 0)), SouthWest),
        CardinalEdge(Point((0, 1)), Point((1, 1)), South),
        CardinalEdge(Point((0, 1)), Point((1, 2)), SouthEast),
        CardinalEdge(Point((0, 2)), Point((0, 1)), West),
        CardinalEdge(Point((0, 2)), Point((0, 3)), East),
        CardinalEdge(Point((0, 2)), Point((1, 1)), SouthWest),
        CardinalEdge(Point((0, 2)), Point((1, 2)), South),
        CardinalEdge(Point((0, 2)), Point((1, 3)), SouthEast),
        CardinalEdge(Point((0, 3)), Point((0, 2)), West),
        CardinalEdge(Point((0, 3)), Point((0, 4)), East),
        CardinalEdge(Point((0, 3)), Point((1, 2)), SouthWest),
        CardinalEdge(Point((0, 3)), Point((1, 3)), South),
        CardinalEdge(Point((0, 3)), Point((1, 4)), SouthEast),
        CardinalEdge(Point((0, 4)), Point((0, 3)), West),
        CardinalEdge(Point((0, 4)), Point((0, 5)), East),
        CardinalEdge(Point((0, 4)), Point((1, 3)), SouthWest),
        CardinalEdge(Point((0, 4)), Point((1, 4)), South),
        CardinalEdge(Point((0, 4)), Point((1, 5)), SouthEast),
        CardinalEdge(Point((0, 5)), Point((0, 4)), West),
        CardinalEdge(Point((0, 5)), Point((0, 6)), East),
        CardinalEdge(Point((0, 5)), Point((1, 4)), SouthWest),
        CardinalEdge(Point((0, 5)), Point((1, 5)), South),
        CardinalEdge(Point((0, 5)), Point((1, 6)), SouthEast),
        CardinalEdge(Point((0, 6)), Point((0, 5)), West),
        CardinalEdge(Point((0, 6)), Point((0, 7)), East),
        CardinalEdge(Point((0, 6)), Point((1, 5)), SouthWest),
        CardinalEdge(Point((0, 6)), Point((1, 6)), South),
        CardinalEdge(Point((0, 6)), Point((1, 7)), SouthEast),

        // South Edge
        CardinalEdge(Point((7, 1)), Point((6, 0)), NorthWest),
        CardinalEdge(Point((7, 1)), Point((6, 1)), North),
        CardinalEdge(Point((7, 1)), Point((6, 2)), NorthEast),
        CardinalEdge(Point((7, 1)), Point((7, 0)), West),
        CardinalEdge(Point((7, 1)), Point((7, 2)), East),
        CardinalEdge(Point((7, 2)), Point((6, 1)), NorthWest),
        CardinalEdge(Point((7, 2)), Point((6, 2)), North),
        CardinalEdge(Point((7, 2)), Point((6, 3)), NorthEast),
        CardinalEdge(Point((7, 2)), Point((7, 1)), West),
        CardinalEdge(Point((7, 2)), Point((7, 3)), East),
        CardinalEdge(Point((7, 3)), Point((6, 2)), NorthWest),
        CardinalEdge(Point((7, 3)), Point((6, 3)), North),
        CardinalEdge(Point((7, 3)), Point((6, 4)), NorthEast),
        CardinalEdge(Point((7, 3)), Point((7, 2)), West),
        CardinalEdge(Point((7, 3)), Point((7, 4)), East),
        CardinalEdge(Point((7, 4)), Point((6, 3)), NorthWest),
        CardinalEdge(Point((7, 4)), Point((6, 4)), North),
        CardinalEdge(Point((7, 4)), Point((6, 5)), NorthEast),
        CardinalEdge(Point((7, 4)), Point((7, 3)), West),
        CardinalEdge(Point((7, 4)), Point((7, 5)), East),
        CardinalEdge(Point((7, 5)), Point((6, 4)), NorthWest),
        CardinalEdge(Point((7, 5)), Point((6, 5)), North),
        CardinalEdge(Point((7, 5)), Point((6, 6)), NorthEast),
        CardinalEdge(Point((7, 5)), Point((7, 4)), West),
        CardinalEdge(Point((7, 5)), Point((7, 6)), East),
        CardinalEdge(Point((7, 6)), Point((6, 5)), NorthWest),
        CardinalEdge(Point((7, 6)), Point((6, 6)), North),
        CardinalEdge(Point((7, 6)), Point((6, 7)), NorthEast),
        CardinalEdge(Point((7, 6)), Point((7, 5)), West),
        CardinalEdge(Point((7, 6)), Point((7, 7)), East),

        // East edge
        CardinalEdge(Point((1, 7)), Point((0, 6)), NorthWest),
        CardinalEdge(Point((1, 7)), Point((0, 7)), North),
        CardinalEdge(Point((1, 7)), Point((1, 6)), West),
        CardinalEdge(Point((1, 7)), Point((2, 6)), SouthWest),
        CardinalEdge(Point((1, 7)), Point((2, 7)), South),
        CardinalEdge(Point((2, 7)), Point((1, 6)), NorthWest),
        CardinalEdge(Point((2, 7)), Point((1, 7)), North),
        CardinalEdge(Point((2, 7)), Point((2, 6)), West),
        CardinalEdge(Point((2, 7)), Point((3, 6)), SouthWest),
        CardinalEdge(Point((2, 7)), Point((3, 7)), South),
        CardinalEdge(Point((3, 7)), Point((2, 6)), NorthWest),
        CardinalEdge(Point((3, 7)), Point((2, 7)), North),
        CardinalEdge(Point((3, 7)), Point((3, 6)), West),
        CardinalEdge(Point((3, 7)), Point((4, 6)), SouthWest),
        CardinalEdge(Point((3, 7)), Point((4, 7)), South),
        CardinalEdge(Point((4, 7)), Point((3, 6)), NorthWest),
        CardinalEdge(Point((4, 7)), Point((3, 7)), North),
        CardinalEdge(Point((4, 7)), Point((4, 6)), West),
        CardinalEdge(Point((4, 7)), Point((5, 6)), SouthWest),
        CardinalEdge(Point((4, 7)), Point((5, 7)), South),
        CardinalEdge(Point((5, 7)), Point((4, 6)), NorthWest),
        CardinalEdge(Point((5, 7)), Point((4, 7)), North),
        CardinalEdge(Point((5, 7)), Point((5, 6)), West),
        CardinalEdge(Point((5, 7)), Point((6, 6)), SouthWest),
        CardinalEdge(Point((5, 7)), Point((6, 7)), South),
        CardinalEdge(Point((6, 7)), Point((5, 6)), NorthWest),
        CardinalEdge(Point((6, 7)), Point((5, 7)), North),
        CardinalEdge(Point((6, 7)), Point((6, 6)), West),
        CardinalEdge(Point((6, 7)), Point((7, 6)), SouthWest),
        CardinalEdge(Point((6, 7)), Point((7, 7)), South),

        // West edge
        CardinalEdge(Point((1, 0)), Point((0, 0)), North),
        CardinalEdge(Point((1, 0)), Point((0, 1)), NorthEast),
        CardinalEdge(Point((1, 0)), Point((1, 1)), East),
        CardinalEdge(Point((1, 0)), Point((2, 0)), South),
        CardinalEdge(Point((1, 0)), Point((2, 1)), SouthEast),
        CardinalEdge(Point((2, 0)), Point((1, 0)), North),
        CardinalEdge(Point((2, 0)), Point((1, 1)), NorthEast),
        CardinalEdge(Point((2, 0)), Point((2, 1)), East),
        CardinalEdge(Point((2, 0)), Point((3, 0)), South),
        CardinalEdge(Point((2, 0)), Point((3, 1)), SouthEast),
        CardinalEdge(Point((3, 0)), Point((2, 0)), North),
        CardinalEdge(Point((3, 0)), Point((2, 1)), NorthEast),
        CardinalEdge(Point((3, 0)), Point((3, 1)), East),
        CardinalEdge(Point((3, 0)), Point((4, 0)), South),
        CardinalEdge(Point((3, 0)), Point((4, 1)), SouthEast),
        CardinalEdge(Point((4, 0)), Point((3, 0)), North),
        CardinalEdge(Point((4, 0)), Point((3, 1)), NorthEast),
        CardinalEdge(Point((4, 0)), Point((4, 1)), East),
        CardinalEdge(Point((4, 0)), Point((5, 0)), South),
        CardinalEdge(Point((4, 0)), Point((5, 1)), SouthEast),
        CardinalEdge(Point((5, 0)), Point((4, 0)), North),
        CardinalEdge(Point((5, 0)), Point((4, 1)), NorthEast),
        CardinalEdge(Point((5, 0)), Point((5, 1)), East),
        CardinalEdge(Point((5, 0)), Point((6, 0)), South),
        CardinalEdge(Point((5, 0)), Point((6, 1)), SouthEast),
        CardinalEdge(Point((6, 0)), Point((5, 0)), North),
        CardinalEdge(Point((6, 0)), Point((5, 1)), NorthEast),
        CardinalEdge(Point((6, 0)), Point((6, 1)), East),
        CardinalEdge(Point((6, 0)), Point((7, 0)), South),
        CardinalEdge(Point((6, 0)), Point((7, 1)), SouthEast),

        // Interior
        CardinalEdge(Point((1, 1)), Point((0, 0)), NorthWest),
        CardinalEdge(Point((1, 1)), Point((0, 1)), North),
        CardinalEdge(Point((1, 1)), Point((0, 2)), NorthEast),
        CardinalEdge(Point((1, 1)), Point((1, 0)), West),
        CardinalEdge(Point((1, 1)), Point((1, 2)), East),
        CardinalEdge(Point((1, 1)), Point((2, 0)), SouthWest),
        CardinalEdge(Point((1, 1)), Point((2, 1)), South),
        CardinalEdge(Point((1, 1)), Point((2, 2)), SouthEast),
        CardinalEdge(Point((1, 2)), Point((0, 1)), NorthWest),
        CardinalEdge(Point((1, 2)), Point((0, 2)), North),
        CardinalEdge(Point((1, 2)), Point((0, 3)), NorthEast),
        CardinalEdge(Point((1, 2)), Point((1, 1)), West),
        CardinalEdge(Point((1, 2)), Point((1, 3)), East),
        CardinalEdge(Point((1, 2)), Point((2, 1)), SouthWest),
        CardinalEdge(Point((1, 2)), Point((2, 2)), South),
        CardinalEdge(Point((1, 2)), Point((2, 3)), SouthEast),
        CardinalEdge(Point((1, 3)), Point((0, 2)), NorthWest),
        CardinalEdge(Point((1, 3)), Point((0, 3)), North),
        CardinalEdge(Point((1, 3)), Point((0, 4)), NorthEast),
        CardinalEdge(Point((1, 3)), Point((1, 2)), West),
        CardinalEdge(Point((1, 3)), Point((1, 4)), East),
        CardinalEdge(Point((1, 3)), Point((2, 2)), SouthWest),
        CardinalEdge(Point((1, 3)), Point((2, 3)), South),
        CardinalEdge(Point((1, 3)), Point((2, 4)), SouthEast),
        CardinalEdge(Point((1, 4)), Point((0, 3)), NorthWest),
        CardinalEdge(Point((1, 4)), Point((0, 4)), North),
        CardinalEdge(Point((1, 4)), Point((0, 5)), NorthEast),
        CardinalEdge(Point((1, 4)), Point((1, 3)), West),
        CardinalEdge(Point((1, 4)), Point((1, 5)), East),
        CardinalEdge(Point((1, 4)), Point((2, 3)), SouthWest),
        CardinalEdge(Point((1, 4)), Point((2, 4)), South),
        CardinalEdge(Point((1, 4)), Point((2, 5)), SouthEast),
        CardinalEdge(Point((1, 5)), Point((0, 4)), NorthWest),
        CardinalEdge(Point((1, 5)), Point((0, 5)), North),
        CardinalEdge(Point((1, 5)), Point((0, 6)), NorthEast),
        CardinalEdge(Point((1, 5)), Point((1, 4)), West),
        CardinalEdge(Point((1, 5)), Point((1, 6)), East),
        CardinalEdge(Point((1, 5)), Point((2, 4)), SouthWest),
        CardinalEdge(Point((1, 5)), Point((2, 5)), South),
        CardinalEdge(Point((1, 5)), Point((2, 6)), SouthEast),
        CardinalEdge(Point((1, 6)), Point((0, 5)), NorthWest),
        CardinalEdge(Point((1, 6)), Point((0, 6)), North),
        CardinalEdge(Point((1, 6)), Point((0, 7)), NorthEast),
        CardinalEdge(Point((1, 6)), Point((1, 5)), West),
        CardinalEdge(Point((1, 6)), Point((1, 7)), East),
        CardinalEdge(Point((1, 6)), Point((2, 5)), SouthWest),
        CardinalEdge(Point((1, 6)), Point((2, 6)), South),
        CardinalEdge(Point((1, 6)), Point((2, 7)), SouthEast),
        CardinalEdge(Point((2, 1)), Point((1, 0)), NorthWest),
        CardinalEdge(Point((2, 1)), Point((1, 1)), North),
        CardinalEdge(Point((2, 1)), Point((1, 2)), NorthEast),
        CardinalEdge(Point((2, 1)), Point((2, 0)), West),
        CardinalEdge(Point((2, 1)), Point((2, 2)), East),
        CardinalEdge(Point((2, 1)), Point((3, 0)), SouthWest),
        CardinalEdge(Point((2, 1)), Point((3, 1)), South),
        CardinalEdge(Point((2, 1)), Point((3, 2)), SouthEast),
        CardinalEdge(Point((2, 2)), Point((1, 1)), NorthWest),
        CardinalEdge(Point((2, 2)), Point((1, 2)), North),
        CardinalEdge(Point((2, 2)), Point((1, 3)), NorthEast),
        CardinalEdge(Point((2, 2)), Point((2, 1)), West),
        CardinalEdge(Point((2, 2)), Point((2, 3)), East),
        CardinalEdge(Point((2, 2)), Point((3, 1)), SouthWest),
        CardinalEdge(Point((2, 2)), Point((3, 2)), South),
        CardinalEdge(Point((2, 2)), Point((3, 3)), SouthEast),
        CardinalEdge(Point((2, 3)), Point((1, 2)), NorthWest),
        CardinalEdge(Point((2, 3)), Point((1, 3)), North),
        CardinalEdge(Point((2, 3)), Point((1, 4)), NorthEast),
        CardinalEdge(Point((2, 3)), Point((2, 2)), West),
        CardinalEdge(Point((2, 3)), Point((2, 4)), East),
        CardinalEdge(Point((2, 3)), Point((3, 2)), SouthWest),
        CardinalEdge(Point((2, 3)), Point((3, 3)), South),
        CardinalEdge(Point((2, 3)), Point((3, 4)), SouthEast),
        CardinalEdge(Point((2, 4)), Point((1, 3)), NorthWest),
        CardinalEdge(Point((2, 4)), Point((1, 4)), North),
        CardinalEdge(Point((2, 4)), Point((1, 5)), NorthEast),
        CardinalEdge(Point((2, 4)), Point((2, 3)), West),
        CardinalEdge(Point((2, 4)), Point((2, 5)), East),
        CardinalEdge(Point((2, 4)), Point((3, 3)), SouthWest),
        CardinalEdge(Point((2, 4)), Point((3, 4)), South),
        CardinalEdge(Point((2, 4)), Point((3, 5)), SouthEast),
        CardinalEdge(Point((2, 5)), Point((1, 4)), NorthWest),
        CardinalEdge(Point((2, 5)), Point((1, 5)), North),
        CardinalEdge(Point((2, 5)), Point((1, 6)), NorthEast),
        CardinalEdge(Point((2, 5)), Point((2, 4)), West),
        CardinalEdge(Point((2, 5)), Point((2, 6)), East),
        CardinalEdge(Point((2, 5)), Point((3, 4)), SouthWest),
        CardinalEdge(Point((2, 5)), Point((3, 5)), South),
        CardinalEdge(Point((2, 5)), Point((3, 6)), SouthEast),
        CardinalEdge(Point((2, 6)), Point((1, 5)), NorthWest),
        CardinalEdge(Point((2, 6)), Point((1, 6)), North),
        CardinalEdge(Point((2, 6)), Point((1, 7)), NorthEast),
        CardinalEdge(Point((2, 6)), Point((2, 5)), West),
        CardinalEdge(Point((2, 6)), Point((2, 7)), East),
        CardinalEdge(Point((2, 6)), Point((3, 5)), SouthWest),
        CardinalEdge(Point((2, 6)), Point((3, 6)), South),
        CardinalEdge(Point((2, 6)), Point((3, 7)), SouthEast),
        CardinalEdge(Point((3, 1)), Point((2, 0)), NorthWest),
        CardinalEdge(Point((3, 1)), Point((2, 1)), North),
        CardinalEdge(Point((3, 1)), Point((2, 2)), NorthEast),
        CardinalEdge(Point((3, 1)), Point((3, 0)), West),
        CardinalEdge(Point((3, 1)), Point((3, 2)), East),
        CardinalEdge(Point((3, 1)), Point((4, 0)), SouthWest),
        CardinalEdge(Point((3, 1)), Point((4, 1)), South),
        CardinalEdge(Point((3, 1)), Point((4, 2)), SouthEast),
        CardinalEdge(Point((3, 2)), Point((2, 1)), NorthWest),
        CardinalEdge(Point((3, 2)), Point((2, 2)), North),
        CardinalEdge(Point((3, 2)), Point((2, 3)), NorthEast),
        CardinalEdge(Point((3, 2)), Point((3, 1)), West),
        CardinalEdge(Point((3, 2)), Point((3, 3)), East),
        CardinalEdge(Point((3, 2)), Point((4, 1)), SouthWest),
        CardinalEdge(Point((3, 2)), Point((4, 2)), South),
        CardinalEdge(Point((3, 2)), Point((4, 3)), SouthEast),
        CardinalEdge(Point((3, 3)), Point((2, 2)), NorthWest),
        CardinalEdge(Point((3, 3)), Point((2, 3)), North),
        CardinalEdge(Point((3, 3)), Point((2, 4)), NorthEast),
        CardinalEdge(Point((3, 3)), Point((3, 2)), West),
        CardinalEdge(Point((3, 3)), Point((3, 4)), East),
        CardinalEdge(Point((3, 3)), Point((4, 2)), SouthWest),
        CardinalEdge(Point((3, 3)), Point((4, 3)), South),
        CardinalEdge(Point((3, 3)), Point((4, 4)), SouthEast),
        CardinalEdge(Point((3, 4)), Point((2, 3)), NorthWest),
        CardinalEdge(Point((3, 4)), Point((2, 4)), North),
        CardinalEdge(Point((3, 4)), Point((2, 5)), NorthEast),
        CardinalEdge(Point((3, 4)), Point((3, 3)), West),
        CardinalEdge(Point((3, 4)), Point((3, 5)), East),
        CardinalEdge(Point((3, 4)), Point((4, 3)), SouthWest),
        CardinalEdge(Point((3, 4)), Point((4, 4)), South),
        CardinalEdge(Point((3, 4)), Point((4, 5)), SouthEast),
        CardinalEdge(Point((3, 5)), Point((2, 4)), NorthWest),
        CardinalEdge(Point((3, 5)), Point((2, 5)), North),
        CardinalEdge(Point((3, 5)), Point((2, 6)), NorthEast),
        CardinalEdge(Point((3, 5)), Point((3, 4)), West),
        CardinalEdge(Point((3, 5)), Point((3, 6)), East),
        CardinalEdge(Point((3, 5)), Point((4, 4)), SouthWest),
        CardinalEdge(Point((3, 5)), Point((4, 5)), South),
        CardinalEdge(Point((3, 5)), Point((4, 6)), SouthEast),
        CardinalEdge(Point((3, 6)), Point((2, 5)), NorthWest),
        CardinalEdge(Point((3, 6)), Point((2, 6)), North),
        CardinalEdge(Point((3, 6)), Point((2, 7)), NorthEast),
        CardinalEdge(Point((3, 6)), Point((3, 5)), West),
        CardinalEdge(Point((3, 6)), Point((3, 7)), East),
        CardinalEdge(Point((3, 6)), Point((4, 5)), SouthWest),
        CardinalEdge(Point((3, 6)), Point((4, 6)), South),
        CardinalEdge(Point((3, 6)), Point((4, 7)), SouthEast),
        CardinalEdge(Point((4, 1)), Point((3, 0)), NorthWest),
        CardinalEdge(Point((4, 1)), Point((3, 1)), North),
        CardinalEdge(Point((4, 1)), Point((3, 2)), NorthEast),
        CardinalEdge(Point((4, 1)), Point((4, 0)), West),
        CardinalEdge(Point((4, 1)), Point((4, 2)), East),
        CardinalEdge(Point((4, 1)), Point((5, 0)), SouthWest),
        CardinalEdge(Point((4, 1)), Point((5, 1)), South),
        CardinalEdge(Point((4, 1)), Point((5, 2)), SouthEast),
        CardinalEdge(Point((4, 2)), Point((3, 1)), NorthWest),
        CardinalEdge(Point((4, 2)), Point((3, 2)), North),
        CardinalEdge(Point((4, 2)), Point((3, 3)), NorthEast),
        CardinalEdge(Point((4, 2)), Point((4, 1)), West),
        CardinalEdge(Point((4, 2)), Point((4, 3)), East),
        CardinalEdge(Point((4, 2)), Point((5, 1)), SouthWest),
        CardinalEdge(Point((4, 2)), Point((5, 2)), South),
        CardinalEdge(Point((4, 2)), Point((5, 3)), SouthEast),
        CardinalEdge(Point((4, 3)), Point((3, 2)), NorthWest),
        CardinalEdge(Point((4, 3)), Point((3, 3)), North),
        CardinalEdge(Point((4, 3)), Point((3, 4)), NorthEast),
        CardinalEdge(Point((4, 3)), Point((4, 2)), West),
        CardinalEdge(Point((4, 3)), Point((4, 4)), East),
        CardinalEdge(Point((4, 3)), Point((5, 2)), SouthWest),
        CardinalEdge(Point((4, 3)), Point((5, 3)), South),
        CardinalEdge(Point((4, 3)), Point((5, 4)), SouthEast),
        CardinalEdge(Point((4, 4)), Point((3, 3)), NorthWest),
        CardinalEdge(Point((4, 4)), Point((3, 4)), North),
        CardinalEdge(Point((4, 4)), Point((3, 5)), NorthEast),
        CardinalEdge(Point((4, 4)), Point((4, 3)), West),
        CardinalEdge(Point((4, 4)), Point((4, 5)), East),
        CardinalEdge(Point((4, 4)), Point((5, 3)), SouthWest),
        CardinalEdge(Point((4, 4)), Point((5, 4)), South),
        CardinalEdge(Point((4, 4)), Point((5, 5)), SouthEast),
        CardinalEdge(Point((4, 5)), Point((3, 4)), NorthWest),
        CardinalEdge(Point((4, 5)), Point((3, 5)), North),
        CardinalEdge(Point((4, 5)), Point((3, 6)), NorthEast),
        CardinalEdge(Point((4, 5)), Point((4, 4)), West),
        CardinalEdge(Point((4, 5)), Point((4, 6)), East),
        CardinalEdge(Point((4, 5)), Point((5, 4)), SouthWest),
        CardinalEdge(Point((4, 5)), Point((5, 5)), South),
        CardinalEdge(Point((4, 5)), Point((5, 6)), SouthEast),
        CardinalEdge(Point((4, 6)), Point((3, 5)), NorthWest),
        CardinalEdge(Point((4, 6)), Point((3, 6)), North),
        CardinalEdge(Point((4, 6)), Point((3, 7)), NorthEast),
        CardinalEdge(Point((4, 6)), Point((4, 5)), West),
        CardinalEdge(Point((4, 6)), Point((4, 7)), East),
        CardinalEdge(Point((4, 6)), Point((5, 5)), SouthWest),
        CardinalEdge(Point((4, 6)), Point((5, 6)), South),
        CardinalEdge(Point((4, 6)), Point((5, 7)), SouthEast),
        CardinalEdge(Point((5, 1)), Point((4, 0)), NorthWest),
        CardinalEdge(Point((5, 1)), Point((4, 1)), North),
        CardinalEdge(Point((5, 1)), Point((4, 2)), NorthEast),
        CardinalEdge(Point((5, 1)), Point((5, 0)), West),
        CardinalEdge(Point((5, 1)), Point((5, 2)), East),
        CardinalEdge(Point((5, 1)), Point((6, 0)), SouthWest),
        CardinalEdge(Point((5, 1)), Point((6, 1)), South),
        CardinalEdge(Point((5, 1)), Point((6, 2)), SouthEast),
        CardinalEdge(Point((5, 2)), Point((4, 1)), NorthWest),
        CardinalEdge(Point((5, 2)), Point((4, 2)), North),
        CardinalEdge(Point((5, 2)), Point((4, 3)), NorthEast),
        CardinalEdge(Point((5, 2)), Point((5, 1)), West),
        CardinalEdge(Point((5, 2)), Point((5, 3)), East),
        CardinalEdge(Point((5, 2)), Point((6, 1)), SouthWest),
        CardinalEdge(Point((5, 2)), Point((6, 2)), South),
        CardinalEdge(Point((5, 2)), Point((6, 3)), SouthEast),
        CardinalEdge(Point((5, 3)), Point((4, 2)), NorthWest),
        CardinalEdge(Point((5, 3)), Point((4, 3)), North),
        CardinalEdge(Point((5, 3)), Point((4, 4)), NorthEast),
        CardinalEdge(Point((5, 3)), Point((5, 2)), West),
        CardinalEdge(Point((5, 3)), Point((5, 4)), East),
        CardinalEdge(Point((5, 3)), Point((6, 2)), SouthWest),
        CardinalEdge(Point((5, 3)), Point((6, 3)), South),
        CardinalEdge(Point((5, 3)), Point((6, 4)), SouthEast),
        CardinalEdge(Point((5, 4)), Point((4, 3)), NorthWest),
        CardinalEdge(Point((5, 4)), Point((4, 4)), North),
        CardinalEdge(Point((5, 4)), Point((4, 5)), NorthEast),
        CardinalEdge(Point((5, 4)), Point((5, 3)), West),
        CardinalEdge(Point((5, 4)), Point((5, 5)), East),
        CardinalEdge(Point((5, 4)), Point((6, 3)), SouthWest),
        CardinalEdge(Point((5, 4)), Point((6, 4)), South),
        CardinalEdge(Point((5, 4)), Point((6, 5)), SouthEast),
        CardinalEdge(Point((5, 5)), Point((4, 4)), NorthWest),
        CardinalEdge(Point((5, 5)), Point((4, 5)), North),
        CardinalEdge(Point((5, 5)), Point((4, 6)), NorthEast),
        CardinalEdge(Point((5, 5)), Point((5, 4)), West),
        CardinalEdge(Point((5, 5)), Point((5, 6)), East),
        CardinalEdge(Point((5, 5)), Point((6, 4)), SouthWest),
        CardinalEdge(Point((5, 5)), Point((6, 5)), South),
        CardinalEdge(Point((5, 5)), Point((6, 6)), SouthEast),
        CardinalEdge(Point((5, 6)), Point((4, 5)), NorthWest),
        CardinalEdge(Point((5, 6)), Point((4, 6)), North),
        CardinalEdge(Point((5, 6)), Point((4, 7)), NorthEast),
        CardinalEdge(Point((5, 6)), Point((5, 5)), West),
        CardinalEdge(Point((5, 6)), Point((5, 7)), East),
        CardinalEdge(Point((5, 6)), Point((6, 5)), SouthWest),
        CardinalEdge(Point((5, 6)), Point((6, 6)), South),
        CardinalEdge(Point((5, 6)), Point((6, 7)), SouthEast),
        CardinalEdge(Point((6, 1)), Point((5, 0)), NorthWest),
        CardinalEdge(Point((6, 1)), Point((5, 1)), North),
        CardinalEdge(Point((6, 1)), Point((5, 2)), NorthEast),
        CardinalEdge(Point((6, 1)), Point((6, 0)), West),
        CardinalEdge(Point((6, 1)), Point((6, 2)), East),
        CardinalEdge(Point((6, 1)), Point((7, 0)), SouthWest),
        CardinalEdge(Point((6, 1)), Point((7, 1)), South),
        CardinalEdge(Point((6, 1)), Point((7, 2)), SouthEast),
        CardinalEdge(Point((6, 2)), Point((5, 1)), NorthWest),
        CardinalEdge(Point((6, 2)), Point((5, 2)), North),
        CardinalEdge(Point((6, 2)), Point((5, 3)), NorthEast),
        CardinalEdge(Point((6, 2)), Point((6, 1)), West),
        CardinalEdge(Point((6, 2)), Point((6, 3)), East),
        CardinalEdge(Point((6, 2)), Point((7, 1)), SouthWest),
        CardinalEdge(Point((6, 2)), Point((7, 2)), South),
        CardinalEdge(Point((6, 2)), Point((7, 3)), SouthEast),
        CardinalEdge(Point((6, 3)), Point((5, 2)), NorthWest),
        CardinalEdge(Point((6, 3)), Point((5, 3)), North),
        CardinalEdge(Point((6, 3)), Point((5, 4)), NorthEast),
        CardinalEdge(Point((6, 3)), Point((6, 2)), West),
        CardinalEdge(Point((6, 3)), Point((6, 4)), East),
        CardinalEdge(Point((6, 3)), Point((7, 2)), SouthWest),
        CardinalEdge(Point((6, 3)), Point((7, 3)), South),
        CardinalEdge(Point((6, 3)), Point((7, 4)), SouthEast),
        CardinalEdge(Point((6, 4)), Point((5, 3)), NorthWest),
        CardinalEdge(Point((6, 4)), Point((5, 4)), North),
        CardinalEdge(Point((6, 4)), Point((5, 5)), NorthEast),
        CardinalEdge(Point((6, 4)), Point((6, 3)), West),
        CardinalEdge(Point((6, 4)), Point((6, 5)), East),
        CardinalEdge(Point((6, 4)), Point((7, 3)), SouthWest),
        CardinalEdge(Point((6, 4)), Point((7, 4)), South),
        CardinalEdge(Point((6, 4)), Point((7, 5)), SouthEast),
        CardinalEdge(Point((6, 5)), Point((5, 4)), NorthWest),
        CardinalEdge(Point((6, 5)), Point((5, 5)), North),
        CardinalEdge(Point((6, 5)), Point((5, 6)), NorthEast),
        CardinalEdge(Point((6, 5)), Point((6, 4)), West),
        CardinalEdge(Point((6, 5)), Point((6, 6)), East),
        CardinalEdge(Point((6, 5)), Point((7, 4)), SouthWest),
        CardinalEdge(Point((6, 5)), Point((7, 5)), South),
        CardinalEdge(Point((6, 5)), Point((7, 6)), SouthEast),
        CardinalEdge(Point((6, 6)), Point((5, 5)), NorthWest),
        CardinalEdge(Point((6, 6)), Point((5, 6)), North),
        CardinalEdge(Point((6, 6)), Point((5, 7)), NorthEast),
        CardinalEdge(Point((6, 6)), Point((6, 5)), West),
        CardinalEdge(Point((6, 6)), Point((6, 7)), East),
        CardinalEdge(Point((6, 6)), Point((7, 5)), SouthWest),
        CardinalEdge(Point((6, 6)), Point((7, 6)), South),
        CardinalEdge(Point((6, 6)), Point((7, 7)), SouthEast)
      )
    )

  val CheckersBoard =
    Graph(
      List(
        Point((0, 0)), Point((1, 0)), Point((2, 0)), Point(3, 0), Point(4, 0), Point((5, 0)), Point((6, 0)), Point((7, 0)),
        Point((0, 1)), Point((1, 1)), Point((2, 1)), Point(3, 1), Point(4, 1), Point((5, 1)), Point((6, 1)), Point((7, 1)),
        Point((0, 2)), Point((1, 2)), Point((2, 2)), Point(3, 2), Point(4, 2), Point((5, 2)), Point((6, 2)), Point((7, 2)),
        Point((0, 3)), Point((1, 3)), Point((2, 3)), Point(3, 3), Point(4, 3), Point((5, 3)), Point((6, 3)), Point((7, 3)),
        Point((0, 4)), Point((1, 4)), Point((2, 4)), Point(3, 4), Point(4, 4), Point((5, 4)), Point((6, 4)), Point((7, 4)),
        Point((0, 5)), Point((1, 5)), Point((2, 5)), Point(3, 5), Point(4, 5), Point((5, 5)), Point((6, 5)), Point((7, 5)),
        Point((0, 6)), Point((1, 6)), Point((2, 6)), Point(3, 6), Point(4, 6), Point((5, 6)), Point((6, 6)), Point((7, 6)),
        Point((0, 8)), Point((1, 8)), Point((2, 8)), Point(3, 8), Point(4, 8), Point((5, 8)), Point((6, 8)), Point((7, 8))
      ),
      List(
        // Northwest corner
        CardinalEdge(Point((0, 0)), Point((0, 1)), East),
        CardinalEdge(Point((0, 0)), Point((1, 0)), South),
        
        // Northeast corner
        CardinalEdge(Point((0, 7)), Point((0, 6)), West),
        CardinalEdge(Point((0, 7)), Point((1, 7)), South),
        

        // Southwest corner
        CardinalEdge(Point((7, 0)), Point((6, 0)), North),
        CardinalEdge(Point((7, 0)), Point((7, 1)), East),

        // Southeast corner
        CardinalEdge(Point((7, 7)), Point((6, 7)), North),
        CardinalEdge(Point((7, 7)), Point((7, 6)), West),

        // North Edge
        CardinalEdge(Point((0, 1)), Point((0, 0)), West),
        CardinalEdge(Point((0, 1)), Point((0, 2)), East),
        CardinalEdge(Point((0, 1)), Point((1, 1)), South),
        CardinalEdge(Point((0, 2)), Point((0, 1)), West),
        CardinalEdge(Point((0, 2)), Point((0, 3)), East),
        CardinalEdge(Point((0, 2)), Point((1, 2)), South),
        CardinalEdge(Point((0, 3)), Point((0, 2)), West),
        CardinalEdge(Point((0, 3)), Point((0, 4)), East),
        CardinalEdge(Point((0, 3)), Point((1, 3)), South),
        CardinalEdge(Point((0, 4)), Point((0, 3)), West),
        CardinalEdge(Point((0, 4)), Point((0, 5)), East),
        CardinalEdge(Point((0, 4)), Point((1, 4)), South),
        CardinalEdge(Point((0, 5)), Point((0, 4)), West),
        CardinalEdge(Point((0, 5)), Point((0, 6)), East),
        CardinalEdge(Point((0, 5)), Point((1, 5)), South),
        CardinalEdge(Point((0, 6)), Point((0, 5)), West),
        CardinalEdge(Point((0, 6)), Point((0, 7)), East),
        CardinalEdge(Point((0, 6)), Point((1, 6)), South),

        // South Edge
        CardinalEdge(Point((7, 1)), Point((6, 1)), North),
        CardinalEdge(Point((7, 1)), Point((7, 0)), West),
        CardinalEdge(Point((7, 1)), Point((7, 2)), East),
        CardinalEdge(Point((7, 2)), Point((6, 2)), North),
        CardinalEdge(Point((7, 2)), Point((7, 1)), West),
        CardinalEdge(Point((7, 2)), Point((7, 3)), East),
        CardinalEdge(Point((7, 3)), Point((6, 3)), North),
        CardinalEdge(Point((7, 3)), Point((7, 2)), West),
        CardinalEdge(Point((7, 3)), Point((7, 4)), East),
        CardinalEdge(Point((7, 4)), Point((6, 4)), North),
        CardinalEdge(Point((7, 4)), Point((7, 3)), West),
        CardinalEdge(Point((7, 4)), Point((7, 5)), East),
        CardinalEdge(Point((7, 5)), Point((6, 5)), North),
        CardinalEdge(Point((7, 5)), Point((7, 4)), West),
        CardinalEdge(Point((7, 5)), Point((7, 6)), East),
        CardinalEdge(Point((7, 6)), Point((6, 6)), North),
        CardinalEdge(Point((7, 6)), Point((7, 5)), West),
        CardinalEdge(Point((7, 6)), Point((7, 7)), East),

        // East edge
        CardinalEdge(Point((1, 7)), Point((0, 7)), North),
        CardinalEdge(Point((1, 7)), Point((1, 6)), West),
        CardinalEdge(Point((1, 7)), Point((2, 7)), South),
        CardinalEdge(Point((2, 7)), Point((1, 7)), North),
        CardinalEdge(Point((2, 7)), Point((2, 6)), West),
        CardinalEdge(Point((2, 7)), Point((3, 7)), South),
        CardinalEdge(Point((3, 7)), Point((2, 7)), North),
        CardinalEdge(Point((3, 7)), Point((3, 6)), West),
        CardinalEdge(Point((3, 7)), Point((4, 7)), South),
        CardinalEdge(Point((4, 7)), Point((3, 7)), North),
        CardinalEdge(Point((4, 7)), Point((4, 6)), West),
        CardinalEdge(Point((4, 7)), Point((5, 7)), South),
        CardinalEdge(Point((5, 7)), Point((4, 7)), North),
        CardinalEdge(Point((5, 7)), Point((5, 6)), West),
        CardinalEdge(Point((5, 7)), Point((6, 7)), South),
        CardinalEdge(Point((6, 7)), Point((5, 7)), North),
        CardinalEdge(Point((6, 7)), Point((6, 6)), West),
        CardinalEdge(Point((6, 7)), Point((7, 7)), South),

        // West edge
        CardinalEdge(Point((1, 0)), Point((0, 0)), North),
        CardinalEdge(Point((1, 0)), Point((1, 1)), East),
        CardinalEdge(Point((1, 0)), Point((2, 0)), South),
        CardinalEdge(Point((2, 0)), Point((1, 0)), North),
        CardinalEdge(Point((2, 0)), Point((2, 1)), East),
        CardinalEdge(Point((2, 0)), Point((3, 0)), South),
        CardinalEdge(Point((3, 0)), Point((2, 0)), North),
        CardinalEdge(Point((3, 0)), Point((3, 1)), East),
        CardinalEdge(Point((3, 0)), Point((4, 0)), South),
        CardinalEdge(Point((4, 0)), Point((3, 0)), North),
        CardinalEdge(Point((4, 0)), Point((4, 1)), East),
        CardinalEdge(Point((4, 0)), Point((5, 0)), South),
        CardinalEdge(Point((5, 0)), Point((4, 0)), North),
        CardinalEdge(Point((5, 0)), Point((5, 1)), East),
        CardinalEdge(Point((5, 0)), Point((6, 0)), South),
        CardinalEdge(Point((6, 0)), Point((5, 0)), North),
        CardinalEdge(Point((6, 0)), Point((6, 1)), East),
        CardinalEdge(Point((6, 0)), Point((7, 0)), South),

        // Interior
        CardinalEdge(Point((1, 1)), Point((0, 1)), North),
        CardinalEdge(Point((1, 1)), Point((1, 0)), West),
        CardinalEdge(Point((1, 1)), Point((1, 2)), East),
        CardinalEdge(Point((1, 1)), Point((2, 1)), South),
        CardinalEdge(Point((1, 2)), Point((0, 2)), North),
        CardinalEdge(Point((1, 2)), Point((1, 1)), West),
        CardinalEdge(Point((1, 2)), Point((1, 3)), East),
        CardinalEdge(Point((1, 2)), Point((2, 2)), South),
        CardinalEdge(Point((1, 3)), Point((0, 3)), North),
        CardinalEdge(Point((1, 3)), Point((1, 2)), West),
        CardinalEdge(Point((1, 3)), Point((1, 4)), East),
        CardinalEdge(Point((1, 3)), Point((2, 3)), South),
        CardinalEdge(Point((1, 4)), Point((0, 4)), North),
        CardinalEdge(Point((1, 4)), Point((1, 3)), West),
        CardinalEdge(Point((1, 4)), Point((1, 5)), East),
        CardinalEdge(Point((1, 4)), Point((2, 4)), South),
        CardinalEdge(Point((1, 5)), Point((0, 5)), North),
        CardinalEdge(Point((1, 5)), Point((1, 4)), West),
        CardinalEdge(Point((1, 5)), Point((1, 6)), East),
        CardinalEdge(Point((1, 5)), Point((2, 5)), South),
        CardinalEdge(Point((1, 6)), Point((0, 6)), North),
        CardinalEdge(Point((1, 6)), Point((1, 5)), West),
        CardinalEdge(Point((1, 6)), Point((1, 7)), East),
        CardinalEdge(Point((1, 6)), Point((2, 6)), South),
        CardinalEdge(Point((2, 1)), Point((1, 1)), North),
        CardinalEdge(Point((2, 1)), Point((2, 0)), West),
        CardinalEdge(Point((2, 1)), Point((2, 2)), East),
        CardinalEdge(Point((2, 1)), Point((3, 1)), South),
        CardinalEdge(Point((2, 2)), Point((1, 2)), North),
        CardinalEdge(Point((2, 2)), Point((2, 1)), West),
        CardinalEdge(Point((2, 2)), Point((2, 3)), East),
        CardinalEdge(Point((2, 2)), Point((3, 2)), South),
        CardinalEdge(Point((2, 3)), Point((1, 3)), North),
        CardinalEdge(Point((2, 3)), Point((2, 2)), West),
        CardinalEdge(Point((2, 3)), Point((2, 4)), East),
        CardinalEdge(Point((2, 3)), Point((3, 3)), South),
        CardinalEdge(Point((2, 4)), Point((1, 4)), North),
        CardinalEdge(Point((2, 4)), Point((2, 3)), West),
        CardinalEdge(Point((2, 4)), Point((2, 5)), East),
        CardinalEdge(Point((2, 4)), Point((3, 4)), South),
        CardinalEdge(Point((2, 5)), Point((1, 5)), North),
        CardinalEdge(Point((2, 5)), Point((2, 4)), West),
        CardinalEdge(Point((2, 5)), Point((2, 6)), East),
        CardinalEdge(Point((2, 5)), Point((3, 5)), South),
        CardinalEdge(Point((2, 6)), Point((1, 6)), North),
        CardinalEdge(Point((2, 6)), Point((2, 5)), West),
        CardinalEdge(Point((2, 6)), Point((2, 7)), East),
        CardinalEdge(Point((2, 6)), Point((3, 6)), South),
        CardinalEdge(Point((3, 1)), Point((2, 1)), North),
        CardinalEdge(Point((3, 1)), Point((3, 0)), West),
        CardinalEdge(Point((3, 1)), Point((3, 2)), East),
        CardinalEdge(Point((3, 1)), Point((4, 1)), South),
        CardinalEdge(Point((3, 2)), Point((2, 2)), North),
        CardinalEdge(Point((3, 2)), Point((3, 1)), West),
        CardinalEdge(Point((3, 2)), Point((3, 3)), East),
        CardinalEdge(Point((3, 2)), Point((4, 2)), South),
        CardinalEdge(Point((3, 3)), Point((2, 3)), North),
        CardinalEdge(Point((3, 3)), Point((3, 2)), West),
        CardinalEdge(Point((3, 3)), Point((3, 4)), East),
        CardinalEdge(Point((3, 3)), Point((4, 3)), South),
        CardinalEdge(Point((3, 4)), Point((2, 4)), North),
        CardinalEdge(Point((3, 4)), Point((3, 3)), West),
        CardinalEdge(Point((3, 4)), Point((3, 5)), East),
        CardinalEdge(Point((3, 4)), Point((4, 4)), South),
        CardinalEdge(Point((3, 5)), Point((2, 5)), North),
        CardinalEdge(Point((3, 5)), Point((3, 4)), West),
        CardinalEdge(Point((3, 5)), Point((3, 6)), East),
        CardinalEdge(Point((3, 5)), Point((4, 5)), South),
        CardinalEdge(Point((3, 6)), Point((2, 6)), North),
        CardinalEdge(Point((3, 6)), Point((3, 5)), West),
        CardinalEdge(Point((3, 6)), Point((3, 7)), East),
        CardinalEdge(Point((3, 6)), Point((4, 6)), South),
        CardinalEdge(Point((4, 1)), Point((3, 1)), North),
        CardinalEdge(Point((4, 1)), Point((4, 0)), West),
        CardinalEdge(Point((4, 1)), Point((4, 2)), East),
        CardinalEdge(Point((4, 1)), Point((5, 1)), South),
        CardinalEdge(Point((4, 2)), Point((3, 2)), North),
        CardinalEdge(Point((4, 2)), Point((4, 1)), West),
        CardinalEdge(Point((4, 2)), Point((4, 3)), East),
        CardinalEdge(Point((4, 2)), Point((5, 2)), South),
        CardinalEdge(Point((4, 3)), Point((3, 3)), North),
        CardinalEdge(Point((4, 3)), Point((4, 2)), West),
        CardinalEdge(Point((4, 3)), Point((4, 4)), East),
        CardinalEdge(Point((4, 3)), Point((5, 3)), South),
        CardinalEdge(Point((4, 4)), Point((3, 4)), North),
        CardinalEdge(Point((4, 4)), Point((4, 3)), West),
        CardinalEdge(Point((4, 4)), Point((4, 5)), East),
        CardinalEdge(Point((4, 4)), Point((5, 4)), South),
        CardinalEdge(Point((4, 5)), Point((3, 5)), North),
        CardinalEdge(Point((4, 5)), Point((4, 4)), West),
        CardinalEdge(Point((4, 5)), Point((4, 6)), East),
        CardinalEdge(Point((4, 5)), Point((5, 5)), South),
        CardinalEdge(Point((4, 6)), Point((3, 6)), North),
        CardinalEdge(Point((4, 6)), Point((4, 5)), West),
        CardinalEdge(Point((4, 6)), Point((4, 7)), East),
        CardinalEdge(Point((4, 6)), Point((5, 6)), South),
        CardinalEdge(Point((5, 1)), Point((4, 1)), North),
        CardinalEdge(Point((5, 1)), Point((5, 0)), West),
        CardinalEdge(Point((5, 1)), Point((5, 2)), East),
        CardinalEdge(Point((5, 1)), Point((6, 1)), South),
        CardinalEdge(Point((5, 2)), Point((4, 2)), North),
        CardinalEdge(Point((5, 2)), Point((5, 1)), West),
        CardinalEdge(Point((5, 2)), Point((5, 3)), East),
        CardinalEdge(Point((5, 2)), Point((6, 2)), South),
        CardinalEdge(Point((5, 3)), Point((4, 3)), North),
        CardinalEdge(Point((5, 3)), Point((5, 2)), West),
        CardinalEdge(Point((5, 3)), Point((5, 4)), East),
        CardinalEdge(Point((5, 3)), Point((6, 3)), South),
        CardinalEdge(Point((5, 4)), Point((4, 4)), North),
        CardinalEdge(Point((5, 4)), Point((5, 3)), West),
        CardinalEdge(Point((5, 4)), Point((5, 5)), East),
        CardinalEdge(Point((5, 4)), Point((6, 4)), South),
        CardinalEdge(Point((5, 5)), Point((4, 5)), North),
        CardinalEdge(Point((5, 5)), Point((5, 4)), West),
        CardinalEdge(Point((5, 5)), Point((5, 6)), East),
        CardinalEdge(Point((5, 5)), Point((6, 5)), South),
        CardinalEdge(Point((5, 6)), Point((4, 6)), North),
        CardinalEdge(Point((5, 6)), Point((5, 5)), West),
        CardinalEdge(Point((5, 6)), Point((5, 7)), East),
        CardinalEdge(Point((5, 6)), Point((6, 6)), South),
        CardinalEdge(Point((6, 1)), Point((5, 1)), North),
        CardinalEdge(Point((6, 1)), Point((6, 0)), West),
        CardinalEdge(Point((6, 1)), Point((6, 2)), East),
        CardinalEdge(Point((6, 1)), Point((7, 1)), South),
        CardinalEdge(Point((6, 2)), Point((5, 2)), North),
        CardinalEdge(Point((6, 2)), Point((6, 1)), West),
        CardinalEdge(Point((6, 2)), Point((6, 3)), East),
        CardinalEdge(Point((6, 2)), Point((7, 2)), South),
        CardinalEdge(Point((6, 3)), Point((5, 3)), North),
        CardinalEdge(Point((6, 3)), Point((6, 2)), West),
        CardinalEdge(Point((6, 3)), Point((6, 4)), East),
        CardinalEdge(Point((6, 3)), Point((7, 3)), South),
        CardinalEdge(Point((6, 4)), Point((5, 4)), North),
        CardinalEdge(Point((6, 4)), Point((6, 3)), West),
        CardinalEdge(Point((6, 4)), Point((6, 5)), East),
        CardinalEdge(Point((6, 4)), Point((7, 4)), South),
        CardinalEdge(Point((6, 5)), Point((5, 5)), North),
        CardinalEdge(Point((6, 5)), Point((6, 4)), West),
        CardinalEdge(Point((6, 5)), Point((6, 6)), East),
        CardinalEdge(Point((6, 5)), Point((7, 5)), South),
        CardinalEdge(Point((6, 6)), Point((5, 6)), North),
        CardinalEdge(Point((6, 6)), Point((6, 5)), West),
        CardinalEdge(Point((6, 6)), Point((6, 7)), East),
        CardinalEdge(Point((6, 6)), Point((7, 6)), South)
      )
    )
}

