package org.beachc.leisurely.ast

import org.beachc.leisurely.implicits._

package object graphs {
  val TTTBoard = 
    Graph(
      List(
        PointNode((0, 0)), PointNode((1, 0)), PointNode((2, 0)), 
        PointNode((0, 1)), PointNode((1, 1)), PointNode((2, 1)), 
        PointNode((0, 2)), PointNode((1, 2)), PointNode((2, 2))
      ),
      List(
        CardinalEdge(PointNode((0, 0)), PointNode((0, 1)), East),
        CardinalEdge(PointNode((0, 0)), PointNode((1, 0)), South), 
        CardinalEdge(PointNode((0, 0)), PointNode((1, 1)), SouthEast),

        CardinalEdge(PointNode((0, 1)), PointNode((0, 0)), West),
        CardinalEdge(PointNode((0, 1)), PointNode((0, 2)), East),
        CardinalEdge(PointNode((0, 1)), PointNode((1, 0)), SouthWest),
        CardinalEdge(PointNode((0, 1)), PointNode((1, 1)), South),
        CardinalEdge(PointNode((0, 1)), PointNode((1, 2)), SouthEast),

        CardinalEdge(PointNode((0, 2)), PointNode((0, 1)), West), 
        CardinalEdge(PointNode((0, 2)), PointNode((1, 1)), SouthWest), 
        CardinalEdge(PointNode((0, 2)), PointNode((1, 2)), South), 

        CardinalEdge(PointNode((1, 0)), PointNode((0, 0)), North),
        CardinalEdge(PointNode((1, 0)), PointNode((0, 1)), NorthEast),
        CardinalEdge(PointNode((1, 0)), PointNode((1, 1)), East),
        CardinalEdge(PointNode((1, 0)), PointNode((2, 0)), South),
        CardinalEdge(PointNode((1, 0)), PointNode((2, 1)), SouthEast),

        CardinalEdge(PointNode((1, 1)), PointNode((0, 0)), NorthWest),
        CardinalEdge(PointNode((1, 1)), PointNode((0, 1)), North),
        CardinalEdge(PointNode((1, 1)), PointNode((0, 2)), NorthEast),
        CardinalEdge(PointNode((1, 1)), PointNode((1, 0)), West),
        CardinalEdge(PointNode((1, 1)), PointNode((1, 2)), East),
        CardinalEdge(PointNode((1, 1)), PointNode((2, 0)), SouthWest),
        CardinalEdge(PointNode((1, 1)), PointNode((2, 1)), South),
        CardinalEdge(PointNode((1, 1)), PointNode((2, 2)), SouthEast),

        CardinalEdge(PointNode((1, 2)), PointNode((0, 1)), NorthWest),
        CardinalEdge(PointNode((1, 2)), PointNode((0, 2)), North),
        CardinalEdge(PointNode((1, 2)), PointNode((1, 1)), West),
        CardinalEdge(PointNode((1, 2)), PointNode((2, 1)), SouthWest),
        CardinalEdge(PointNode((1, 2)), PointNode((2, 2)), South),

        CardinalEdge(PointNode((2, 0)), PointNode((1, 0)), North),
        CardinalEdge(PointNode((2, 0)), PointNode((1, 1)), NorthEast),
        CardinalEdge(PointNode((2, 0)), PointNode((2, 1)), East),

        CardinalEdge(PointNode((2, 1)), PointNode((1, 0)), NorthWest),
        CardinalEdge(PointNode((2, 1)), PointNode((1, 1)), North),
        CardinalEdge(PointNode((2, 1)), PointNode((1, 2)), NorthEast),
        CardinalEdge(PointNode((2, 1)), PointNode((2, 0)), West), 
        CardinalEdge(PointNode((2, 1)), PointNode((2, 2)), East),

        CardinalEdge(PointNode((2, 2)), PointNode((1, 1)), NorthWest),
        CardinalEdge(PointNode((2, 2)), PointNode((1, 2)), North),
        CardinalEdge(PointNode((2, 2)), PointNode((2, 1)), West)
      )
    )

  val ChessBoard =
    Graph(
      List(
        PointNode((0, 0)), PointNode((1, 0)), PointNode((2, 0)), PointNode(3, 0), PointNode(4, 0), PointNode((5, 0)), PointNode((6, 0)), PointNode((7, 0)),
        PointNode((0, 1)), PointNode((1, 1)), PointNode((2, 1)), PointNode(3, 1), PointNode(4, 1), PointNode((5, 1)), PointNode((6, 1)), PointNode((7, 1)),
        PointNode((0, 2)), PointNode((1, 2)), PointNode((2, 2)), PointNode(3, 2), PointNode(4, 2), PointNode((5, 2)), PointNode((6, 2)), PointNode((7, 2)),
        PointNode((0, 3)), PointNode((1, 3)), PointNode((2, 3)), PointNode(3, 3), PointNode(4, 3), PointNode((5, 3)), PointNode((6, 3)), PointNode((7, 3)),
        PointNode((0, 4)), PointNode((1, 4)), PointNode((2, 4)), PointNode(3, 4), PointNode(4, 4), PointNode((5, 4)), PointNode((6, 4)), PointNode((7, 4)),
        PointNode((0, 5)), PointNode((1, 5)), PointNode((2, 5)), PointNode(3, 5), PointNode(4, 5), PointNode((5, 5)), PointNode((6, 5)), PointNode((7, 5)),
        PointNode((0, 6)), PointNode((1, 6)), PointNode((2, 6)), PointNode(3, 6), PointNode(4, 6), PointNode((5, 6)), PointNode((6, 6)), PointNode((7, 6)),
        PointNode((0, 8)), PointNode((1, 8)), PointNode((2, 8)), PointNode(3, 8), PointNode(4, 8), PointNode((5, 8)), PointNode((6, 8)), PointNode((7, 8))
      ),
      List(
        // Northwest corner
        CardinalEdge(PointNode((0, 0)), PointNode((0, 1)), East),
        CardinalEdge(PointNode((0, 0)), PointNode((1, 0)), South),
        CardinalEdge(PointNode((0, 0)), PointNode((1, 1)), SouthEast),
        
        // Northeast corner
        CardinalEdge(PointNode((0, 7)), PointNode((0, 6)), West),
        CardinalEdge(PointNode((0, 7)), PointNode((1, 6)), SouthWest),
        CardinalEdge(PointNode((0, 7)), PointNode((1, 7)), South),
        

        // Southwest corner
        CardinalEdge(PointNode((7, 0)), PointNode((6, 0)), North),
        CardinalEdge(PointNode((7, 0)), PointNode((6, 1)), NorthEast),
        CardinalEdge(PointNode((7, 0)), PointNode((7, 1)), East),

        // Southeast corner
        CardinalEdge(PointNode((7, 7)), PointNode((6, 6)), NorthWest),
        CardinalEdge(PointNode((7, 7)), PointNode((6, 7)), North),
        CardinalEdge(PointNode((7, 7)), PointNode((7, 6)), West),

        // North Edge
        CardinalEdge(PointNode((0, 1)), PointNode((0, 0)), West),
        CardinalEdge(PointNode((0, 1)), PointNode((0, 2)), East),
        CardinalEdge(PointNode((0, 1)), PointNode((1, 0)), SouthWest),
        CardinalEdge(PointNode((0, 1)), PointNode((1, 1)), South),
        CardinalEdge(PointNode((0, 1)), PointNode((1, 2)), SouthEast),
        CardinalEdge(PointNode((0, 2)), PointNode((0, 1)), West),
        CardinalEdge(PointNode((0, 2)), PointNode((0, 3)), East),
        CardinalEdge(PointNode((0, 2)), PointNode((1, 1)), SouthWest),
        CardinalEdge(PointNode((0, 2)), PointNode((1, 2)), South),
        CardinalEdge(PointNode((0, 2)), PointNode((1, 3)), SouthEast),
        CardinalEdge(PointNode((0, 3)), PointNode((0, 2)), West),
        CardinalEdge(PointNode((0, 3)), PointNode((0, 4)), East),
        CardinalEdge(PointNode((0, 3)), PointNode((1, 2)), SouthWest),
        CardinalEdge(PointNode((0, 3)), PointNode((1, 3)), South),
        CardinalEdge(PointNode((0, 3)), PointNode((1, 4)), SouthEast),
        CardinalEdge(PointNode((0, 4)), PointNode((0, 3)), West),
        CardinalEdge(PointNode((0, 4)), PointNode((0, 5)), East),
        CardinalEdge(PointNode((0, 4)), PointNode((1, 3)), SouthWest),
        CardinalEdge(PointNode((0, 4)), PointNode((1, 4)), South),
        CardinalEdge(PointNode((0, 4)), PointNode((1, 5)), SouthEast),
        CardinalEdge(PointNode((0, 5)), PointNode((0, 4)), West),
        CardinalEdge(PointNode((0, 5)), PointNode((0, 6)), East),
        CardinalEdge(PointNode((0, 5)), PointNode((1, 4)), SouthWest),
        CardinalEdge(PointNode((0, 5)), PointNode((1, 5)), South),
        CardinalEdge(PointNode((0, 5)), PointNode((1, 6)), SouthEast),
        CardinalEdge(PointNode((0, 6)), PointNode((0, 5)), West),
        CardinalEdge(PointNode((0, 6)), PointNode((0, 7)), East),
        CardinalEdge(PointNode((0, 6)), PointNode((1, 5)), SouthWest),
        CardinalEdge(PointNode((0, 6)), PointNode((1, 6)), South),
        CardinalEdge(PointNode((0, 6)), PointNode((1, 7)), SouthEast),

        // South Edge
        CardinalEdge(PointNode((7, 1)), PointNode((6, 0)), NorthWest),
        CardinalEdge(PointNode((7, 1)), PointNode((6, 1)), North),
        CardinalEdge(PointNode((7, 1)), PointNode((6, 2)), NorthEast),
        CardinalEdge(PointNode((7, 1)), PointNode((7, 0)), West),
        CardinalEdge(PointNode((7, 1)), PointNode((7, 2)), East),
        CardinalEdge(PointNode((7, 2)), PointNode((6, 1)), NorthWest),
        CardinalEdge(PointNode((7, 2)), PointNode((6, 2)), North),
        CardinalEdge(PointNode((7, 2)), PointNode((6, 3)), NorthEast),
        CardinalEdge(PointNode((7, 2)), PointNode((7, 1)), West),
        CardinalEdge(PointNode((7, 2)), PointNode((7, 3)), East),
        CardinalEdge(PointNode((7, 3)), PointNode((6, 2)), NorthWest),
        CardinalEdge(PointNode((7, 3)), PointNode((6, 3)), North),
        CardinalEdge(PointNode((7, 3)), PointNode((6, 4)), NorthEast),
        CardinalEdge(PointNode((7, 3)), PointNode((7, 2)), West),
        CardinalEdge(PointNode((7, 3)), PointNode((7, 4)), East),
        CardinalEdge(PointNode((7, 4)), PointNode((6, 3)), NorthWest),
        CardinalEdge(PointNode((7, 4)), PointNode((6, 4)), North),
        CardinalEdge(PointNode((7, 4)), PointNode((6, 5)), NorthEast),
        CardinalEdge(PointNode((7, 4)), PointNode((7, 3)), West),
        CardinalEdge(PointNode((7, 4)), PointNode((7, 5)), East),
        CardinalEdge(PointNode((7, 5)), PointNode((6, 4)), NorthWest),
        CardinalEdge(PointNode((7, 5)), PointNode((6, 5)), North),
        CardinalEdge(PointNode((7, 5)), PointNode((6, 6)), NorthEast),
        CardinalEdge(PointNode((7, 5)), PointNode((7, 4)), West),
        CardinalEdge(PointNode((7, 5)), PointNode((7, 6)), East),
        CardinalEdge(PointNode((7, 6)), PointNode((6, 5)), NorthWest),
        CardinalEdge(PointNode((7, 6)), PointNode((6, 6)), North),
        CardinalEdge(PointNode((7, 6)), PointNode((6, 7)), NorthEast),
        CardinalEdge(PointNode((7, 6)), PointNode((7, 5)), West),
        CardinalEdge(PointNode((7, 6)), PointNode((7, 7)), East),

        // East edge
        CardinalEdge(PointNode((1, 7)), PointNode((0, 6)), NorthWest),
        CardinalEdge(PointNode((1, 7)), PointNode((0, 7)), North),
        CardinalEdge(PointNode((1, 7)), PointNode((1, 6)), West),
        CardinalEdge(PointNode((1, 7)), PointNode((2, 6)), SouthWest),
        CardinalEdge(PointNode((1, 7)), PointNode((2, 7)), South),
        CardinalEdge(PointNode((2, 7)), PointNode((1, 6)), NorthWest),
        CardinalEdge(PointNode((2, 7)), PointNode((1, 7)), North),
        CardinalEdge(PointNode((2, 7)), PointNode((2, 6)), West),
        CardinalEdge(PointNode((2, 7)), PointNode((3, 6)), SouthWest),
        CardinalEdge(PointNode((2, 7)), PointNode((3, 7)), South),
        CardinalEdge(PointNode((3, 7)), PointNode((2, 6)), NorthWest),
        CardinalEdge(PointNode((3, 7)), PointNode((2, 7)), North),
        CardinalEdge(PointNode((3, 7)), PointNode((3, 6)), West),
        CardinalEdge(PointNode((3, 7)), PointNode((4, 6)), SouthWest),
        CardinalEdge(PointNode((3, 7)), PointNode((4, 7)), South),
        CardinalEdge(PointNode((4, 7)), PointNode((3, 6)), NorthWest),
        CardinalEdge(PointNode((4, 7)), PointNode((3, 7)), North),
        CardinalEdge(PointNode((4, 7)), PointNode((4, 6)), West),
        CardinalEdge(PointNode((4, 7)), PointNode((5, 6)), SouthWest),
        CardinalEdge(PointNode((4, 7)), PointNode((5, 7)), South),
        CardinalEdge(PointNode((5, 7)), PointNode((4, 6)), NorthWest),
        CardinalEdge(PointNode((5, 7)), PointNode((4, 7)), North),
        CardinalEdge(PointNode((5, 7)), PointNode((5, 6)), West),
        CardinalEdge(PointNode((5, 7)), PointNode((6, 6)), SouthWest),
        CardinalEdge(PointNode((5, 7)), PointNode((6, 7)), South),
        CardinalEdge(PointNode((6, 7)), PointNode((5, 6)), NorthWest),
        CardinalEdge(PointNode((6, 7)), PointNode((5, 7)), North),
        CardinalEdge(PointNode((6, 7)), PointNode((6, 6)), West),
        CardinalEdge(PointNode((6, 7)), PointNode((7, 6)), SouthWest),
        CardinalEdge(PointNode((6, 7)), PointNode((7, 7)), South),

        // West edge
        CardinalEdge(PointNode((1, 0)), PointNode((0, 0)), North),
        CardinalEdge(PointNode((1, 0)), PointNode((0, 1)), NorthEast),
        CardinalEdge(PointNode((1, 0)), PointNode((1, 1)), East),
        CardinalEdge(PointNode((1, 0)), PointNode((2, 0)), South),
        CardinalEdge(PointNode((1, 0)), PointNode((2, 1)), SouthEast),
        CardinalEdge(PointNode((2, 0)), PointNode((1, 0)), North),
        CardinalEdge(PointNode((2, 0)), PointNode((1, 1)), NorthEast),
        CardinalEdge(PointNode((2, 0)), PointNode((2, 1)), East),
        CardinalEdge(PointNode((2, 0)), PointNode((3, 0)), South),
        CardinalEdge(PointNode((2, 0)), PointNode((3, 1)), SouthEast),
        CardinalEdge(PointNode((3, 0)), PointNode((2, 0)), North),
        CardinalEdge(PointNode((3, 0)), PointNode((2, 1)), NorthEast),
        CardinalEdge(PointNode((3, 0)), PointNode((3, 1)), East),
        CardinalEdge(PointNode((3, 0)), PointNode((4, 0)), South),
        CardinalEdge(PointNode((3, 0)), PointNode((4, 1)), SouthEast),
        CardinalEdge(PointNode((4, 0)), PointNode((3, 0)), North),
        CardinalEdge(PointNode((4, 0)), PointNode((3, 1)), NorthEast),
        CardinalEdge(PointNode((4, 0)), PointNode((4, 1)), East),
        CardinalEdge(PointNode((4, 0)), PointNode((5, 0)), South),
        CardinalEdge(PointNode((4, 0)), PointNode((5, 1)), SouthEast),
        CardinalEdge(PointNode((5, 0)), PointNode((4, 0)), North),
        CardinalEdge(PointNode((5, 0)), PointNode((4, 1)), NorthEast),
        CardinalEdge(PointNode((5, 0)), PointNode((5, 1)), East),
        CardinalEdge(PointNode((5, 0)), PointNode((6, 0)), South),
        CardinalEdge(PointNode((5, 0)), PointNode((6, 1)), SouthEast),
        CardinalEdge(PointNode((6, 0)), PointNode((5, 0)), North),
        CardinalEdge(PointNode((6, 0)), PointNode((5, 1)), NorthEast),
        CardinalEdge(PointNode((6, 0)), PointNode((6, 1)), East),
        CardinalEdge(PointNode((6, 0)), PointNode((7, 0)), South),
        CardinalEdge(PointNode((6, 0)), PointNode((7, 1)), SouthEast),

        // Interior
        CardinalEdge(PointNode((1, 1)), PointNode((0, 0)), NorthWest),
        CardinalEdge(PointNode((1, 1)), PointNode((0, 1)), North),
        CardinalEdge(PointNode((1, 1)), PointNode((0, 2)), NorthEast),
        CardinalEdge(PointNode((1, 1)), PointNode((1, 0)), West),
        CardinalEdge(PointNode((1, 1)), PointNode((1, 2)), East),
        CardinalEdge(PointNode((1, 1)), PointNode((2, 0)), SouthWest),
        CardinalEdge(PointNode((1, 1)), PointNode((2, 1)), South),
        CardinalEdge(PointNode((1, 1)), PointNode((2, 2)), SouthEast),
        CardinalEdge(PointNode((1, 2)), PointNode((0, 1)), NorthWest),
        CardinalEdge(PointNode((1, 2)), PointNode((0, 2)), North),
        CardinalEdge(PointNode((1, 2)), PointNode((0, 3)), NorthEast),
        CardinalEdge(PointNode((1, 2)), PointNode((1, 1)), West),
        CardinalEdge(PointNode((1, 2)), PointNode((1, 3)), East),
        CardinalEdge(PointNode((1, 2)), PointNode((2, 1)), SouthWest),
        CardinalEdge(PointNode((1, 2)), PointNode((2, 2)), South),
        CardinalEdge(PointNode((1, 2)), PointNode((2, 3)), SouthEast),
        CardinalEdge(PointNode((1, 3)), PointNode((0, 2)), NorthWest),
        CardinalEdge(PointNode((1, 3)), PointNode((0, 3)), North),
        CardinalEdge(PointNode((1, 3)), PointNode((0, 4)), NorthEast),
        CardinalEdge(PointNode((1, 3)), PointNode((1, 2)), West),
        CardinalEdge(PointNode((1, 3)), PointNode((1, 4)), East),
        CardinalEdge(PointNode((1, 3)), PointNode((2, 2)), SouthWest),
        CardinalEdge(PointNode((1, 3)), PointNode((2, 3)), South),
        CardinalEdge(PointNode((1, 3)), PointNode((2, 4)), SouthEast),
        CardinalEdge(PointNode((1, 4)), PointNode((0, 3)), NorthWest),
        CardinalEdge(PointNode((1, 4)), PointNode((0, 4)), North),
        CardinalEdge(PointNode((1, 4)), PointNode((0, 5)), NorthEast),
        CardinalEdge(PointNode((1, 4)), PointNode((1, 3)), West),
        CardinalEdge(PointNode((1, 4)), PointNode((1, 5)), East),
        CardinalEdge(PointNode((1, 4)), PointNode((2, 3)), SouthWest),
        CardinalEdge(PointNode((1, 4)), PointNode((2, 4)), South),
        CardinalEdge(PointNode((1, 4)), PointNode((2, 5)), SouthEast),
        CardinalEdge(PointNode((1, 5)), PointNode((0, 4)), NorthWest),
        CardinalEdge(PointNode((1, 5)), PointNode((0, 5)), North),
        CardinalEdge(PointNode((1, 5)), PointNode((0, 6)), NorthEast),
        CardinalEdge(PointNode((1, 5)), PointNode((1, 4)), West),
        CardinalEdge(PointNode((1, 5)), PointNode((1, 6)), East),
        CardinalEdge(PointNode((1, 5)), PointNode((2, 4)), SouthWest),
        CardinalEdge(PointNode((1, 5)), PointNode((2, 5)), South),
        CardinalEdge(PointNode((1, 5)), PointNode((2, 6)), SouthEast),
        CardinalEdge(PointNode((1, 6)), PointNode((0, 5)), NorthWest),
        CardinalEdge(PointNode((1, 6)), PointNode((0, 6)), North),
        CardinalEdge(PointNode((1, 6)), PointNode((0, 7)), NorthEast),
        CardinalEdge(PointNode((1, 6)), PointNode((1, 5)), West),
        CardinalEdge(PointNode((1, 6)), PointNode((1, 7)), East),
        CardinalEdge(PointNode((1, 6)), PointNode((2, 5)), SouthWest),
        CardinalEdge(PointNode((1, 6)), PointNode((2, 6)), South),
        CardinalEdge(PointNode((1, 6)), PointNode((2, 7)), SouthEast),
        CardinalEdge(PointNode((2, 1)), PointNode((1, 0)), NorthWest),
        CardinalEdge(PointNode((2, 1)), PointNode((1, 1)), North),
        CardinalEdge(PointNode((2, 1)), PointNode((1, 2)), NorthEast),
        CardinalEdge(PointNode((2, 1)), PointNode((2, 0)), West),
        CardinalEdge(PointNode((2, 1)), PointNode((2, 2)), East),
        CardinalEdge(PointNode((2, 1)), PointNode((3, 0)), SouthWest),
        CardinalEdge(PointNode((2, 1)), PointNode((3, 1)), South),
        CardinalEdge(PointNode((2, 1)), PointNode((3, 2)), SouthEast),
        CardinalEdge(PointNode((2, 2)), PointNode((1, 1)), NorthWest),
        CardinalEdge(PointNode((2, 2)), PointNode((1, 2)), North),
        CardinalEdge(PointNode((2, 2)), PointNode((1, 3)), NorthEast),
        CardinalEdge(PointNode((2, 2)), PointNode((2, 1)), West),
        CardinalEdge(PointNode((2, 2)), PointNode((2, 3)), East),
        CardinalEdge(PointNode((2, 2)), PointNode((3, 1)), SouthWest),
        CardinalEdge(PointNode((2, 2)), PointNode((3, 2)), South),
        CardinalEdge(PointNode((2, 2)), PointNode((3, 3)), SouthEast),
        CardinalEdge(PointNode((2, 3)), PointNode((1, 2)), NorthWest),
        CardinalEdge(PointNode((2, 3)), PointNode((1, 3)), North),
        CardinalEdge(PointNode((2, 3)), PointNode((1, 4)), NorthEast),
        CardinalEdge(PointNode((2, 3)), PointNode((2, 2)), West),
        CardinalEdge(PointNode((2, 3)), PointNode((2, 4)), East),
        CardinalEdge(PointNode((2, 3)), PointNode((3, 2)), SouthWest),
        CardinalEdge(PointNode((2, 3)), PointNode((3, 3)), South),
        CardinalEdge(PointNode((2, 3)), PointNode((3, 4)), SouthEast),
        CardinalEdge(PointNode((2, 4)), PointNode((1, 3)), NorthWest),
        CardinalEdge(PointNode((2, 4)), PointNode((1, 4)), North),
        CardinalEdge(PointNode((2, 4)), PointNode((1, 5)), NorthEast),
        CardinalEdge(PointNode((2, 4)), PointNode((2, 3)), West),
        CardinalEdge(PointNode((2, 4)), PointNode((2, 5)), East),
        CardinalEdge(PointNode((2, 4)), PointNode((3, 3)), SouthWest),
        CardinalEdge(PointNode((2, 4)), PointNode((3, 4)), South),
        CardinalEdge(PointNode((2, 4)), PointNode((3, 5)), SouthEast),
        CardinalEdge(PointNode((2, 5)), PointNode((1, 4)), NorthWest),
        CardinalEdge(PointNode((2, 5)), PointNode((1, 5)), North),
        CardinalEdge(PointNode((2, 5)), PointNode((1, 6)), NorthEast),
        CardinalEdge(PointNode((2, 5)), PointNode((2, 4)), West),
        CardinalEdge(PointNode((2, 5)), PointNode((2, 6)), East),
        CardinalEdge(PointNode((2, 5)), PointNode((3, 4)), SouthWest),
        CardinalEdge(PointNode((2, 5)), PointNode((3, 5)), South),
        CardinalEdge(PointNode((2, 5)), PointNode((3, 6)), SouthEast),
        CardinalEdge(PointNode((2, 6)), PointNode((1, 5)), NorthWest),
        CardinalEdge(PointNode((2, 6)), PointNode((1, 6)), North),
        CardinalEdge(PointNode((2, 6)), PointNode((1, 7)), NorthEast),
        CardinalEdge(PointNode((2, 6)), PointNode((2, 5)), West),
        CardinalEdge(PointNode((2, 6)), PointNode((2, 7)), East),
        CardinalEdge(PointNode((2, 6)), PointNode((3, 5)), SouthWest),
        CardinalEdge(PointNode((2, 6)), PointNode((3, 6)), South),
        CardinalEdge(PointNode((2, 6)), PointNode((3, 7)), SouthEast),
        CardinalEdge(PointNode((3, 1)), PointNode((2, 0)), NorthWest),
        CardinalEdge(PointNode((3, 1)), PointNode((2, 1)), North),
        CardinalEdge(PointNode((3, 1)), PointNode((2, 2)), NorthEast),
        CardinalEdge(PointNode((3, 1)), PointNode((3, 0)), West),
        CardinalEdge(PointNode((3, 1)), PointNode((3, 2)), East),
        CardinalEdge(PointNode((3, 1)), PointNode((4, 0)), SouthWest),
        CardinalEdge(PointNode((3, 1)), PointNode((4, 1)), South),
        CardinalEdge(PointNode((3, 1)), PointNode((4, 2)), SouthEast),
        CardinalEdge(PointNode((3, 2)), PointNode((2, 1)), NorthWest),
        CardinalEdge(PointNode((3, 2)), PointNode((2, 2)), North),
        CardinalEdge(PointNode((3, 2)), PointNode((2, 3)), NorthEast),
        CardinalEdge(PointNode((3, 2)), PointNode((3, 1)), West),
        CardinalEdge(PointNode((3, 2)), PointNode((3, 3)), East),
        CardinalEdge(PointNode((3, 2)), PointNode((4, 1)), SouthWest),
        CardinalEdge(PointNode((3, 2)), PointNode((4, 2)), South),
        CardinalEdge(PointNode((3, 2)), PointNode((4, 3)), SouthEast),
        CardinalEdge(PointNode((3, 3)), PointNode((2, 2)), NorthWest),
        CardinalEdge(PointNode((3, 3)), PointNode((2, 3)), North),
        CardinalEdge(PointNode((3, 3)), PointNode((2, 4)), NorthEast),
        CardinalEdge(PointNode((3, 3)), PointNode((3, 2)), West),
        CardinalEdge(PointNode((3, 3)), PointNode((3, 4)), East),
        CardinalEdge(PointNode((3, 3)), PointNode((4, 2)), SouthWest),
        CardinalEdge(PointNode((3, 3)), PointNode((4, 3)), South),
        CardinalEdge(PointNode((3, 3)), PointNode((4, 4)), SouthEast),
        CardinalEdge(PointNode((3, 4)), PointNode((2, 3)), NorthWest),
        CardinalEdge(PointNode((3, 4)), PointNode((2, 4)), North),
        CardinalEdge(PointNode((3, 4)), PointNode((2, 5)), NorthEast),
        CardinalEdge(PointNode((3, 4)), PointNode((3, 3)), West),
        CardinalEdge(PointNode((3, 4)), PointNode((3, 5)), East),
        CardinalEdge(PointNode((3, 4)), PointNode((4, 3)), SouthWest),
        CardinalEdge(PointNode((3, 4)), PointNode((4, 4)), South),
        CardinalEdge(PointNode((3, 4)), PointNode((4, 5)), SouthEast),
        CardinalEdge(PointNode((3, 5)), PointNode((2, 4)), NorthWest),
        CardinalEdge(PointNode((3, 5)), PointNode((2, 5)), North),
        CardinalEdge(PointNode((3, 5)), PointNode((2, 6)), NorthEast),
        CardinalEdge(PointNode((3, 5)), PointNode((3, 4)), West),
        CardinalEdge(PointNode((3, 5)), PointNode((3, 6)), East),
        CardinalEdge(PointNode((3, 5)), PointNode((4, 4)), SouthWest),
        CardinalEdge(PointNode((3, 5)), PointNode((4, 5)), South),
        CardinalEdge(PointNode((3, 5)), PointNode((4, 6)), SouthEast),
        CardinalEdge(PointNode((3, 6)), PointNode((2, 5)), NorthWest),
        CardinalEdge(PointNode((3, 6)), PointNode((2, 6)), North),
        CardinalEdge(PointNode((3, 6)), PointNode((2, 7)), NorthEast),
        CardinalEdge(PointNode((3, 6)), PointNode((3, 5)), West),
        CardinalEdge(PointNode((3, 6)), PointNode((3, 7)), East),
        CardinalEdge(PointNode((3, 6)), PointNode((4, 5)), SouthWest),
        CardinalEdge(PointNode((3, 6)), PointNode((4, 6)), South),
        CardinalEdge(PointNode((3, 6)), PointNode((4, 7)), SouthEast),
        CardinalEdge(PointNode((4, 1)), PointNode((3, 0)), NorthWest),
        CardinalEdge(PointNode((4, 1)), PointNode((3, 1)), North),
        CardinalEdge(PointNode((4, 1)), PointNode((3, 2)), NorthEast),
        CardinalEdge(PointNode((4, 1)), PointNode((4, 0)), West),
        CardinalEdge(PointNode((4, 1)), PointNode((4, 2)), East),
        CardinalEdge(PointNode((4, 1)), PointNode((5, 0)), SouthWest),
        CardinalEdge(PointNode((4, 1)), PointNode((5, 1)), South),
        CardinalEdge(PointNode((4, 1)), PointNode((5, 2)), SouthEast),
        CardinalEdge(PointNode((4, 2)), PointNode((3, 1)), NorthWest),
        CardinalEdge(PointNode((4, 2)), PointNode((3, 2)), North),
        CardinalEdge(PointNode((4, 2)), PointNode((3, 3)), NorthEast),
        CardinalEdge(PointNode((4, 2)), PointNode((4, 1)), West),
        CardinalEdge(PointNode((4, 2)), PointNode((4, 3)), East),
        CardinalEdge(PointNode((4, 2)), PointNode((5, 1)), SouthWest),
        CardinalEdge(PointNode((4, 2)), PointNode((5, 2)), South),
        CardinalEdge(PointNode((4, 2)), PointNode((5, 3)), SouthEast),
        CardinalEdge(PointNode((4, 3)), PointNode((3, 2)), NorthWest),
        CardinalEdge(PointNode((4, 3)), PointNode((3, 3)), North),
        CardinalEdge(PointNode((4, 3)), PointNode((3, 4)), NorthEast),
        CardinalEdge(PointNode((4, 3)), PointNode((4, 2)), West),
        CardinalEdge(PointNode((4, 3)), PointNode((4, 4)), East),
        CardinalEdge(PointNode((4, 3)), PointNode((5, 2)), SouthWest),
        CardinalEdge(PointNode((4, 3)), PointNode((5, 3)), South),
        CardinalEdge(PointNode((4, 3)), PointNode((5, 4)), SouthEast),
        CardinalEdge(PointNode((4, 4)), PointNode((3, 3)), NorthWest),
        CardinalEdge(PointNode((4, 4)), PointNode((3, 4)), North),
        CardinalEdge(PointNode((4, 4)), PointNode((3, 5)), NorthEast),
        CardinalEdge(PointNode((4, 4)), PointNode((4, 3)), West),
        CardinalEdge(PointNode((4, 4)), PointNode((4, 5)), East),
        CardinalEdge(PointNode((4, 4)), PointNode((5, 3)), SouthWest),
        CardinalEdge(PointNode((4, 4)), PointNode((5, 4)), South),
        CardinalEdge(PointNode((4, 4)), PointNode((5, 5)), SouthEast),
        CardinalEdge(PointNode((4, 5)), PointNode((3, 4)), NorthWest),
        CardinalEdge(PointNode((4, 5)), PointNode((3, 5)), North),
        CardinalEdge(PointNode((4, 5)), PointNode((3, 6)), NorthEast),
        CardinalEdge(PointNode((4, 5)), PointNode((4, 4)), West),
        CardinalEdge(PointNode((4, 5)), PointNode((4, 6)), East),
        CardinalEdge(PointNode((4, 5)), PointNode((5, 4)), SouthWest),
        CardinalEdge(PointNode((4, 5)), PointNode((5, 5)), South),
        CardinalEdge(PointNode((4, 5)), PointNode((5, 6)), SouthEast),
        CardinalEdge(PointNode((4, 6)), PointNode((3, 5)), NorthWest),
        CardinalEdge(PointNode((4, 6)), PointNode((3, 6)), North),
        CardinalEdge(PointNode((4, 6)), PointNode((3, 7)), NorthEast),
        CardinalEdge(PointNode((4, 6)), PointNode((4, 5)), West),
        CardinalEdge(PointNode((4, 6)), PointNode((4, 7)), East),
        CardinalEdge(PointNode((4, 6)), PointNode((5, 5)), SouthWest),
        CardinalEdge(PointNode((4, 6)), PointNode((5, 6)), South),
        CardinalEdge(PointNode((4, 6)), PointNode((5, 7)), SouthEast),
        CardinalEdge(PointNode((5, 1)), PointNode((4, 0)), NorthWest),
        CardinalEdge(PointNode((5, 1)), PointNode((4, 1)), North),
        CardinalEdge(PointNode((5, 1)), PointNode((4, 2)), NorthEast),
        CardinalEdge(PointNode((5, 1)), PointNode((5, 0)), West),
        CardinalEdge(PointNode((5, 1)), PointNode((5, 2)), East),
        CardinalEdge(PointNode((5, 1)), PointNode((6, 0)), SouthWest),
        CardinalEdge(PointNode((5, 1)), PointNode((6, 1)), South),
        CardinalEdge(PointNode((5, 1)), PointNode((6, 2)), SouthEast),
        CardinalEdge(PointNode((5, 2)), PointNode((4, 1)), NorthWest),
        CardinalEdge(PointNode((5, 2)), PointNode((4, 2)), North),
        CardinalEdge(PointNode((5, 2)), PointNode((4, 3)), NorthEast),
        CardinalEdge(PointNode((5, 2)), PointNode((5, 1)), West),
        CardinalEdge(PointNode((5, 2)), PointNode((5, 3)), East),
        CardinalEdge(PointNode((5, 2)), PointNode((6, 1)), SouthWest),
        CardinalEdge(PointNode((5, 2)), PointNode((6, 2)), South),
        CardinalEdge(PointNode((5, 2)), PointNode((6, 3)), SouthEast),
        CardinalEdge(PointNode((5, 3)), PointNode((4, 2)), NorthWest),
        CardinalEdge(PointNode((5, 3)), PointNode((4, 3)), North),
        CardinalEdge(PointNode((5, 3)), PointNode((4, 4)), NorthEast),
        CardinalEdge(PointNode((5, 3)), PointNode((5, 2)), West),
        CardinalEdge(PointNode((5, 3)), PointNode((5, 4)), East),
        CardinalEdge(PointNode((5, 3)), PointNode((6, 2)), SouthWest),
        CardinalEdge(PointNode((5, 3)), PointNode((6, 3)), South),
        CardinalEdge(PointNode((5, 3)), PointNode((6, 4)), SouthEast),
        CardinalEdge(PointNode((5, 4)), PointNode((4, 3)), NorthWest),
        CardinalEdge(PointNode((5, 4)), PointNode((4, 4)), North),
        CardinalEdge(PointNode((5, 4)), PointNode((4, 5)), NorthEast),
        CardinalEdge(PointNode((5, 4)), PointNode((5, 3)), West),
        CardinalEdge(PointNode((5, 4)), PointNode((5, 5)), East),
        CardinalEdge(PointNode((5, 4)), PointNode((6, 3)), SouthWest),
        CardinalEdge(PointNode((5, 4)), PointNode((6, 4)), South),
        CardinalEdge(PointNode((5, 4)), PointNode((6, 5)), SouthEast),
        CardinalEdge(PointNode((5, 5)), PointNode((4, 4)), NorthWest),
        CardinalEdge(PointNode((5, 5)), PointNode((4, 5)), North),
        CardinalEdge(PointNode((5, 5)), PointNode((4, 6)), NorthEast),
        CardinalEdge(PointNode((5, 5)), PointNode((5, 4)), West),
        CardinalEdge(PointNode((5, 5)), PointNode((5, 6)), East),
        CardinalEdge(PointNode((5, 5)), PointNode((6, 4)), SouthWest),
        CardinalEdge(PointNode((5, 5)), PointNode((6, 5)), South),
        CardinalEdge(PointNode((5, 5)), PointNode((6, 6)), SouthEast),
        CardinalEdge(PointNode((5, 6)), PointNode((4, 5)), NorthWest),
        CardinalEdge(PointNode((5, 6)), PointNode((4, 6)), North),
        CardinalEdge(PointNode((5, 6)), PointNode((4, 7)), NorthEast),
        CardinalEdge(PointNode((5, 6)), PointNode((5, 5)), West),
        CardinalEdge(PointNode((5, 6)), PointNode((5, 7)), East),
        CardinalEdge(PointNode((5, 6)), PointNode((6, 5)), SouthWest),
        CardinalEdge(PointNode((5, 6)), PointNode((6, 6)), South),
        CardinalEdge(PointNode((5, 6)), PointNode((6, 7)), SouthEast),
        CardinalEdge(PointNode((6, 1)), PointNode((5, 0)), NorthWest),
        CardinalEdge(PointNode((6, 1)), PointNode((5, 1)), North),
        CardinalEdge(PointNode((6, 1)), PointNode((5, 2)), NorthEast),
        CardinalEdge(PointNode((6, 1)), PointNode((6, 0)), West),
        CardinalEdge(PointNode((6, 1)), PointNode((6, 2)), East),
        CardinalEdge(PointNode((6, 1)), PointNode((7, 0)), SouthWest),
        CardinalEdge(PointNode((6, 1)), PointNode((7, 1)), South),
        CardinalEdge(PointNode((6, 1)), PointNode((7, 2)), SouthEast),
        CardinalEdge(PointNode((6, 2)), PointNode((5, 1)), NorthWest),
        CardinalEdge(PointNode((6, 2)), PointNode((5, 2)), North),
        CardinalEdge(PointNode((6, 2)), PointNode((5, 3)), NorthEast),
        CardinalEdge(PointNode((6, 2)), PointNode((6, 1)), West),
        CardinalEdge(PointNode((6, 2)), PointNode((6, 3)), East),
        CardinalEdge(PointNode((6, 2)), PointNode((7, 1)), SouthWest),
        CardinalEdge(PointNode((6, 2)), PointNode((7, 2)), South),
        CardinalEdge(PointNode((6, 2)), PointNode((7, 3)), SouthEast),
        CardinalEdge(PointNode((6, 3)), PointNode((5, 2)), NorthWest),
        CardinalEdge(PointNode((6, 3)), PointNode((5, 3)), North),
        CardinalEdge(PointNode((6, 3)), PointNode((5, 4)), NorthEast),
        CardinalEdge(PointNode((6, 3)), PointNode((6, 2)), West),
        CardinalEdge(PointNode((6, 3)), PointNode((6, 4)), East),
        CardinalEdge(PointNode((6, 3)), PointNode((7, 2)), SouthWest),
        CardinalEdge(PointNode((6, 3)), PointNode((7, 3)), South),
        CardinalEdge(PointNode((6, 3)), PointNode((7, 4)), SouthEast),
        CardinalEdge(PointNode((6, 4)), PointNode((5, 3)), NorthWest),
        CardinalEdge(PointNode((6, 4)), PointNode((5, 4)), North),
        CardinalEdge(PointNode((6, 4)), PointNode((5, 5)), NorthEast),
        CardinalEdge(PointNode((6, 4)), PointNode((6, 3)), West),
        CardinalEdge(PointNode((6, 4)), PointNode((6, 5)), East),
        CardinalEdge(PointNode((6, 4)), PointNode((7, 3)), SouthWest),
        CardinalEdge(PointNode((6, 4)), PointNode((7, 4)), South),
        CardinalEdge(PointNode((6, 4)), PointNode((7, 5)), SouthEast),
        CardinalEdge(PointNode((6, 5)), PointNode((5, 4)), NorthWest),
        CardinalEdge(PointNode((6, 5)), PointNode((5, 5)), North),
        CardinalEdge(PointNode((6, 5)), PointNode((5, 6)), NorthEast),
        CardinalEdge(PointNode((6, 5)), PointNode((6, 4)), West),
        CardinalEdge(PointNode((6, 5)), PointNode((6, 6)), East),
        CardinalEdge(PointNode((6, 5)), PointNode((7, 4)), SouthWest),
        CardinalEdge(PointNode((6, 5)), PointNode((7, 5)), South),
        CardinalEdge(PointNode((6, 5)), PointNode((7, 6)), SouthEast),
        CardinalEdge(PointNode((6, 6)), PointNode((5, 5)), NorthWest),
        CardinalEdge(PointNode((6, 6)), PointNode((5, 6)), North),
        CardinalEdge(PointNode((6, 6)), PointNode((5, 7)), NorthEast),
        CardinalEdge(PointNode((6, 6)), PointNode((6, 5)), West),
        CardinalEdge(PointNode((6, 6)), PointNode((6, 7)), East),
        CardinalEdge(PointNode((6, 6)), PointNode((7, 5)), SouthWest),
        CardinalEdge(PointNode((6, 6)), PointNode((7, 6)), South),
        CardinalEdge(PointNode((6, 6)), PointNode((7, 7)), SouthEast)
      )
    )

  val CheckersBoard =
    Graph(
      List(
        PointNode((0, 0)), PointNode((1, 0)), PointNode((2, 0)), PointNode(3, 0), PointNode(4, 0), PointNode((5, 0)), PointNode((6, 0)), PointNode((7, 0)),
        PointNode((0, 1)), PointNode((1, 1)), PointNode((2, 1)), PointNode(3, 1), PointNode(4, 1), PointNode((5, 1)), PointNode((6, 1)), PointNode((7, 1)),
        PointNode((0, 2)), PointNode((1, 2)), PointNode((2, 2)), PointNode(3, 2), PointNode(4, 2), PointNode((5, 2)), PointNode((6, 2)), PointNode((7, 2)),
        PointNode((0, 3)), PointNode((1, 3)), PointNode((2, 3)), PointNode(3, 3), PointNode(4, 3), PointNode((5, 3)), PointNode((6, 3)), PointNode((7, 3)),
        PointNode((0, 4)), PointNode((1, 4)), PointNode((2, 4)), PointNode(3, 4), PointNode(4, 4), PointNode((5, 4)), PointNode((6, 4)), PointNode((7, 4)),
        PointNode((0, 5)), PointNode((1, 5)), PointNode((2, 5)), PointNode(3, 5), PointNode(4, 5), PointNode((5, 5)), PointNode((6, 5)), PointNode((7, 5)),
        PointNode((0, 6)), PointNode((1, 6)), PointNode((2, 6)), PointNode(3, 6), PointNode(4, 6), PointNode((5, 6)), PointNode((6, 6)), PointNode((7, 6)),
        PointNode((0, 8)), PointNode((1, 8)), PointNode((2, 8)), PointNode(3, 8), PointNode(4, 8), PointNode((5, 8)), PointNode((6, 8)), PointNode((7, 8))
      ),
      List(
        // Northwest corner
        CardinalEdge(PointNode((0, 0)), PointNode((0, 1)), East),
        CardinalEdge(PointNode((0, 0)), PointNode((1, 0)), South),
        
        // Northeast corner
        CardinalEdge(PointNode((0, 7)), PointNode((0, 6)), West),
        CardinalEdge(PointNode((0, 7)), PointNode((1, 7)), South),
        

        // Southwest corner
        CardinalEdge(PointNode((7, 0)), PointNode((6, 0)), North),
        CardinalEdge(PointNode((7, 0)), PointNode((7, 1)), East),

        // Southeast corner
        CardinalEdge(PointNode((7, 7)), PointNode((6, 7)), North),
        CardinalEdge(PointNode((7, 7)), PointNode((7, 6)), West),

        // North Edge
        CardinalEdge(PointNode((0, 1)), PointNode((0, 0)), West),
        CardinalEdge(PointNode((0, 1)), PointNode((0, 2)), East),
        CardinalEdge(PointNode((0, 1)), PointNode((1, 1)), South),
        CardinalEdge(PointNode((0, 2)), PointNode((0, 1)), West),
        CardinalEdge(PointNode((0, 2)), PointNode((0, 3)), East),
        CardinalEdge(PointNode((0, 2)), PointNode((1, 2)), South),
        CardinalEdge(PointNode((0, 3)), PointNode((0, 2)), West),
        CardinalEdge(PointNode((0, 3)), PointNode((0, 4)), East),
        CardinalEdge(PointNode((0, 3)), PointNode((1, 3)), South),
        CardinalEdge(PointNode((0, 4)), PointNode((0, 3)), West),
        CardinalEdge(PointNode((0, 4)), PointNode((0, 5)), East),
        CardinalEdge(PointNode((0, 4)), PointNode((1, 4)), South),
        CardinalEdge(PointNode((0, 5)), PointNode((0, 4)), West),
        CardinalEdge(PointNode((0, 5)), PointNode((0, 6)), East),
        CardinalEdge(PointNode((0, 5)), PointNode((1, 5)), South),
        CardinalEdge(PointNode((0, 6)), PointNode((0, 5)), West),
        CardinalEdge(PointNode((0, 6)), PointNode((0, 7)), East),
        CardinalEdge(PointNode((0, 6)), PointNode((1, 6)), South),

        // South Edge
        CardinalEdge(PointNode((7, 1)), PointNode((6, 1)), North),
        CardinalEdge(PointNode((7, 1)), PointNode((7, 0)), West),
        CardinalEdge(PointNode((7, 1)), PointNode((7, 2)), East),
        CardinalEdge(PointNode((7, 2)), PointNode((6, 2)), North),
        CardinalEdge(PointNode((7, 2)), PointNode((7, 1)), West),
        CardinalEdge(PointNode((7, 2)), PointNode((7, 3)), East),
        CardinalEdge(PointNode((7, 3)), PointNode((6, 3)), North),
        CardinalEdge(PointNode((7, 3)), PointNode((7, 2)), West),
        CardinalEdge(PointNode((7, 3)), PointNode((7, 4)), East),
        CardinalEdge(PointNode((7, 4)), PointNode((6, 4)), North),
        CardinalEdge(PointNode((7, 4)), PointNode((7, 3)), West),
        CardinalEdge(PointNode((7, 4)), PointNode((7, 5)), East),
        CardinalEdge(PointNode((7, 5)), PointNode((6, 5)), North),
        CardinalEdge(PointNode((7, 5)), PointNode((7, 4)), West),
        CardinalEdge(PointNode((7, 5)), PointNode((7, 6)), East),
        CardinalEdge(PointNode((7, 6)), PointNode((6, 6)), North),
        CardinalEdge(PointNode((7, 6)), PointNode((7, 5)), West),
        CardinalEdge(PointNode((7, 6)), PointNode((7, 7)), East),

        // East edge
        CardinalEdge(PointNode((1, 7)), PointNode((0, 7)), North),
        CardinalEdge(PointNode((1, 7)), PointNode((1, 6)), West),
        CardinalEdge(PointNode((1, 7)), PointNode((2, 7)), South),
        CardinalEdge(PointNode((2, 7)), PointNode((1, 7)), North),
        CardinalEdge(PointNode((2, 7)), PointNode((2, 6)), West),
        CardinalEdge(PointNode((2, 7)), PointNode((3, 7)), South),
        CardinalEdge(PointNode((3, 7)), PointNode((2, 7)), North),
        CardinalEdge(PointNode((3, 7)), PointNode((3, 6)), West),
        CardinalEdge(PointNode((3, 7)), PointNode((4, 7)), South),
        CardinalEdge(PointNode((4, 7)), PointNode((3, 7)), North),
        CardinalEdge(PointNode((4, 7)), PointNode((4, 6)), West),
        CardinalEdge(PointNode((4, 7)), PointNode((5, 7)), South),
        CardinalEdge(PointNode((5, 7)), PointNode((4, 7)), North),
        CardinalEdge(PointNode((5, 7)), PointNode((5, 6)), West),
        CardinalEdge(PointNode((5, 7)), PointNode((6, 7)), South),
        CardinalEdge(PointNode((6, 7)), PointNode((5, 7)), North),
        CardinalEdge(PointNode((6, 7)), PointNode((6, 6)), West),
        CardinalEdge(PointNode((6, 7)), PointNode((7, 7)), South),

        // West edge
        CardinalEdge(PointNode((1, 0)), PointNode((0, 0)), North),
        CardinalEdge(PointNode((1, 0)), PointNode((1, 1)), East),
        CardinalEdge(PointNode((1, 0)), PointNode((2, 0)), South),
        CardinalEdge(PointNode((2, 0)), PointNode((1, 0)), North),
        CardinalEdge(PointNode((2, 0)), PointNode((2, 1)), East),
        CardinalEdge(PointNode((2, 0)), PointNode((3, 0)), South),
        CardinalEdge(PointNode((3, 0)), PointNode((2, 0)), North),
        CardinalEdge(PointNode((3, 0)), PointNode((3, 1)), East),
        CardinalEdge(PointNode((3, 0)), PointNode((4, 0)), South),
        CardinalEdge(PointNode((4, 0)), PointNode((3, 0)), North),
        CardinalEdge(PointNode((4, 0)), PointNode((4, 1)), East),
        CardinalEdge(PointNode((4, 0)), PointNode((5, 0)), South),
        CardinalEdge(PointNode((5, 0)), PointNode((4, 0)), North),
        CardinalEdge(PointNode((5, 0)), PointNode((5, 1)), East),
        CardinalEdge(PointNode((5, 0)), PointNode((6, 0)), South),
        CardinalEdge(PointNode((6, 0)), PointNode((5, 0)), North),
        CardinalEdge(PointNode((6, 0)), PointNode((6, 1)), East),
        CardinalEdge(PointNode((6, 0)), PointNode((7, 0)), South),

        // Interior
        CardinalEdge(PointNode((1, 1)), PointNode((0, 1)), North),
        CardinalEdge(PointNode((1, 1)), PointNode((1, 0)), West),
        CardinalEdge(PointNode((1, 1)), PointNode((1, 2)), East),
        CardinalEdge(PointNode((1, 1)), PointNode((2, 1)), South),
        CardinalEdge(PointNode((1, 2)), PointNode((0, 2)), North),
        CardinalEdge(PointNode((1, 2)), PointNode((1, 1)), West),
        CardinalEdge(PointNode((1, 2)), PointNode((1, 3)), East),
        CardinalEdge(PointNode((1, 2)), PointNode((2, 2)), South),
        CardinalEdge(PointNode((1, 3)), PointNode((0, 3)), North),
        CardinalEdge(PointNode((1, 3)), PointNode((1, 2)), West),
        CardinalEdge(PointNode((1, 3)), PointNode((1, 4)), East),
        CardinalEdge(PointNode((1, 3)), PointNode((2, 3)), South),
        CardinalEdge(PointNode((1, 4)), PointNode((0, 4)), North),
        CardinalEdge(PointNode((1, 4)), PointNode((1, 3)), West),
        CardinalEdge(PointNode((1, 4)), PointNode((1, 5)), East),
        CardinalEdge(PointNode((1, 4)), PointNode((2, 4)), South),
        CardinalEdge(PointNode((1, 5)), PointNode((0, 5)), North),
        CardinalEdge(PointNode((1, 5)), PointNode((1, 4)), West),
        CardinalEdge(PointNode((1, 5)), PointNode((1, 6)), East),
        CardinalEdge(PointNode((1, 5)), PointNode((2, 5)), South),
        CardinalEdge(PointNode((1, 6)), PointNode((0, 6)), North),
        CardinalEdge(PointNode((1, 6)), PointNode((1, 5)), West),
        CardinalEdge(PointNode((1, 6)), PointNode((1, 7)), East),
        CardinalEdge(PointNode((1, 6)), PointNode((2, 6)), South),
        CardinalEdge(PointNode((2, 1)), PointNode((1, 1)), North),
        CardinalEdge(PointNode((2, 1)), PointNode((2, 0)), West),
        CardinalEdge(PointNode((2, 1)), PointNode((2, 2)), East),
        CardinalEdge(PointNode((2, 1)), PointNode((3, 1)), South),
        CardinalEdge(PointNode((2, 2)), PointNode((1, 2)), North),
        CardinalEdge(PointNode((2, 2)), PointNode((2, 1)), West),
        CardinalEdge(PointNode((2, 2)), PointNode((2, 3)), East),
        CardinalEdge(PointNode((2, 2)), PointNode((3, 2)), South),
        CardinalEdge(PointNode((2, 3)), PointNode((1, 3)), North),
        CardinalEdge(PointNode((2, 3)), PointNode((2, 2)), West),
        CardinalEdge(PointNode((2, 3)), PointNode((2, 4)), East),
        CardinalEdge(PointNode((2, 3)), PointNode((3, 3)), South),
        CardinalEdge(PointNode((2, 4)), PointNode((1, 4)), North),
        CardinalEdge(PointNode((2, 4)), PointNode((2, 3)), West),
        CardinalEdge(PointNode((2, 4)), PointNode((2, 5)), East),
        CardinalEdge(PointNode((2, 4)), PointNode((3, 4)), South),
        CardinalEdge(PointNode((2, 5)), PointNode((1, 5)), North),
        CardinalEdge(PointNode((2, 5)), PointNode((2, 4)), West),
        CardinalEdge(PointNode((2, 5)), PointNode((2, 6)), East),
        CardinalEdge(PointNode((2, 5)), PointNode((3, 5)), South),
        CardinalEdge(PointNode((2, 6)), PointNode((1, 6)), North),
        CardinalEdge(PointNode((2, 6)), PointNode((2, 5)), West),
        CardinalEdge(PointNode((2, 6)), PointNode((2, 7)), East),
        CardinalEdge(PointNode((2, 6)), PointNode((3, 6)), South),
        CardinalEdge(PointNode((3, 1)), PointNode((2, 1)), North),
        CardinalEdge(PointNode((3, 1)), PointNode((3, 0)), West),
        CardinalEdge(PointNode((3, 1)), PointNode((3, 2)), East),
        CardinalEdge(PointNode((3, 1)), PointNode((4, 1)), South),
        CardinalEdge(PointNode((3, 2)), PointNode((2, 2)), North),
        CardinalEdge(PointNode((3, 2)), PointNode((3, 1)), West),
        CardinalEdge(PointNode((3, 2)), PointNode((3, 3)), East),
        CardinalEdge(PointNode((3, 2)), PointNode((4, 2)), South),
        CardinalEdge(PointNode((3, 3)), PointNode((2, 3)), North),
        CardinalEdge(PointNode((3, 3)), PointNode((3, 2)), West),
        CardinalEdge(PointNode((3, 3)), PointNode((3, 4)), East),
        CardinalEdge(PointNode((3, 3)), PointNode((4, 3)), South),
        CardinalEdge(PointNode((3, 4)), PointNode((2, 4)), North),
        CardinalEdge(PointNode((3, 4)), PointNode((3, 3)), West),
        CardinalEdge(PointNode((3, 4)), PointNode((3, 5)), East),
        CardinalEdge(PointNode((3, 4)), PointNode((4, 4)), South),
        CardinalEdge(PointNode((3, 5)), PointNode((2, 5)), North),
        CardinalEdge(PointNode((3, 5)), PointNode((3, 4)), West),
        CardinalEdge(PointNode((3, 5)), PointNode((3, 6)), East),
        CardinalEdge(PointNode((3, 5)), PointNode((4, 5)), South),
        CardinalEdge(PointNode((3, 6)), PointNode((2, 6)), North),
        CardinalEdge(PointNode((3, 6)), PointNode((3, 5)), West),
        CardinalEdge(PointNode((3, 6)), PointNode((3, 7)), East),
        CardinalEdge(PointNode((3, 6)), PointNode((4, 6)), South),
        CardinalEdge(PointNode((4, 1)), PointNode((3, 1)), North),
        CardinalEdge(PointNode((4, 1)), PointNode((4, 0)), West),
        CardinalEdge(PointNode((4, 1)), PointNode((4, 2)), East),
        CardinalEdge(PointNode((4, 1)), PointNode((5, 1)), South),
        CardinalEdge(PointNode((4, 2)), PointNode((3, 2)), North),
        CardinalEdge(PointNode((4, 2)), PointNode((4, 1)), West),
        CardinalEdge(PointNode((4, 2)), PointNode((4, 3)), East),
        CardinalEdge(PointNode((4, 2)), PointNode((5, 2)), South),
        CardinalEdge(PointNode((4, 3)), PointNode((3, 3)), North),
        CardinalEdge(PointNode((4, 3)), PointNode((4, 2)), West),
        CardinalEdge(PointNode((4, 3)), PointNode((4, 4)), East),
        CardinalEdge(PointNode((4, 3)), PointNode((5, 3)), South),
        CardinalEdge(PointNode((4, 4)), PointNode((3, 4)), North),
        CardinalEdge(PointNode((4, 4)), PointNode((4, 3)), West),
        CardinalEdge(PointNode((4, 4)), PointNode((4, 5)), East),
        CardinalEdge(PointNode((4, 4)), PointNode((5, 4)), South),
        CardinalEdge(PointNode((4, 5)), PointNode((3, 5)), North),
        CardinalEdge(PointNode((4, 5)), PointNode((4, 4)), West),
        CardinalEdge(PointNode((4, 5)), PointNode((4, 6)), East),
        CardinalEdge(PointNode((4, 5)), PointNode((5, 5)), South),
        CardinalEdge(PointNode((4, 6)), PointNode((3, 6)), North),
        CardinalEdge(PointNode((4, 6)), PointNode((4, 5)), West),
        CardinalEdge(PointNode((4, 6)), PointNode((4, 7)), East),
        CardinalEdge(PointNode((4, 6)), PointNode((5, 6)), South),
        CardinalEdge(PointNode((5, 1)), PointNode((4, 1)), North),
        CardinalEdge(PointNode((5, 1)), PointNode((5, 0)), West),
        CardinalEdge(PointNode((5, 1)), PointNode((5, 2)), East),
        CardinalEdge(PointNode((5, 1)), PointNode((6, 1)), South),
        CardinalEdge(PointNode((5, 2)), PointNode((4, 2)), North),
        CardinalEdge(PointNode((5, 2)), PointNode((5, 1)), West),
        CardinalEdge(PointNode((5, 2)), PointNode((5, 3)), East),
        CardinalEdge(PointNode((5, 2)), PointNode((6, 2)), South),
        CardinalEdge(PointNode((5, 3)), PointNode((4, 3)), North),
        CardinalEdge(PointNode((5, 3)), PointNode((5, 2)), West),
        CardinalEdge(PointNode((5, 3)), PointNode((5, 4)), East),
        CardinalEdge(PointNode((5, 3)), PointNode((6, 3)), South),
        CardinalEdge(PointNode((5, 4)), PointNode((4, 4)), North),
        CardinalEdge(PointNode((5, 4)), PointNode((5, 3)), West),
        CardinalEdge(PointNode((5, 4)), PointNode((5, 5)), East),
        CardinalEdge(PointNode((5, 4)), PointNode((6, 4)), South),
        CardinalEdge(PointNode((5, 5)), PointNode((4, 5)), North),
        CardinalEdge(PointNode((5, 5)), PointNode((5, 4)), West),
        CardinalEdge(PointNode((5, 5)), PointNode((5, 6)), East),
        CardinalEdge(PointNode((5, 5)), PointNode((6, 5)), South),
        CardinalEdge(PointNode((5, 6)), PointNode((4, 6)), North),
        CardinalEdge(PointNode((5, 6)), PointNode((5, 5)), West),
        CardinalEdge(PointNode((5, 6)), PointNode((5, 7)), East),
        CardinalEdge(PointNode((5, 6)), PointNode((6, 6)), South),
        CardinalEdge(PointNode((6, 1)), PointNode((5, 1)), North),
        CardinalEdge(PointNode((6, 1)), PointNode((6, 0)), West),
        CardinalEdge(PointNode((6, 1)), PointNode((6, 2)), East),
        CardinalEdge(PointNode((6, 1)), PointNode((7, 1)), South),
        CardinalEdge(PointNode((6, 2)), PointNode((5, 2)), North),
        CardinalEdge(PointNode((6, 2)), PointNode((6, 1)), West),
        CardinalEdge(PointNode((6, 2)), PointNode((6, 3)), East),
        CardinalEdge(PointNode((6, 2)), PointNode((7, 2)), South),
        CardinalEdge(PointNode((6, 3)), PointNode((5, 3)), North),
        CardinalEdge(PointNode((6, 3)), PointNode((6, 2)), West),
        CardinalEdge(PointNode((6, 3)), PointNode((6, 4)), East),
        CardinalEdge(PointNode((6, 3)), PointNode((7, 3)), South),
        CardinalEdge(PointNode((6, 4)), PointNode((5, 4)), North),
        CardinalEdge(PointNode((6, 4)), PointNode((6, 3)), West),
        CardinalEdge(PointNode((6, 4)), PointNode((6, 5)), East),
        CardinalEdge(PointNode((6, 4)), PointNode((7, 4)), South),
        CardinalEdge(PointNode((6, 5)), PointNode((5, 5)), North),
        CardinalEdge(PointNode((6, 5)), PointNode((6, 4)), West),
        CardinalEdge(PointNode((6, 5)), PointNode((6, 6)), East),
        CardinalEdge(PointNode((6, 5)), PointNode((7, 5)), South),
        CardinalEdge(PointNode((6, 6)), PointNode((5, 6)), North),
        CardinalEdge(PointNode((6, 6)), PointNode((6, 5)), West),
        CardinalEdge(PointNode((6, 6)), PointNode((6, 7)), East),
        CardinalEdge(PointNode((6, 6)), PointNode((7, 6)), South)
      )
    )
}

