package org.leisurely_script.gdl.types

/**
  * Created by mcsmash on 1/25/16.
  */
case class LongExpression(value:Long) extends AnyValExpression[Long] {
  override def evaluate:Option[Long] = Some(value)
  def !=(other: DoubleExpression): BooleanExpression = BooleanExpression(value != other.value)
  def !=(other: FloatExpression): BooleanExpression = BooleanExpression(value != other.value)
  def !=(other: LongExpression): BooleanExpression = BooleanExpression(value != other.value)
  def !=(other: IntExpression): BooleanExpression = BooleanExpression(value != other.value)
  def !=(other: CharExpression): BooleanExpression = BooleanExpression(value != other.value)
  def !=(other: ShortExpression): BooleanExpression = BooleanExpression(value != other.value)
  def !=(other: ByteExpression): BooleanExpression = BooleanExpression(value != other.value)
  def %(other: DoubleExpression): DoubleExpression = DoubleExpression(value % other.value)
  def %(other: FloatExpression): FloatExpression = FloatExpression(value % other.value)
  def %(other: LongExpression): LongExpression = LongExpression(value % other.value)
  def %(other: IntExpression): LongExpression = LongExpression(value % other.value)
  def %(other: CharExpression): LongExpression = LongExpression(value % other.value)
  def %(other: ShortExpression): LongExpression = LongExpression(value % other.value)
  def %(other: ByteExpression): LongExpression = LongExpression(value % other.value)
  def &(other: LongExpression): LongExpression = LongExpression(value & other.value)
  def &(other: IntExpression): LongExpression = LongExpression(value & other.value)
  def &(other: CharExpression): LongExpression = LongExpression(value & other.value)
  def &(other: ShortExpression): LongExpression = LongExpression(value & other.value)
  def &(other: ByteExpression): LongExpression = LongExpression(value & other.value)
  def *(other: DoubleExpression): DoubleExpression = DoubleExpression(value * other.value)
  def *(other: FloatExpression): FloatExpression = FloatExpression(value * other.value)
  def *(other: LongExpression): LongExpression = LongExpression(value * other.value)
  def *(other: IntExpression): LongExpression = LongExpression(value * other.value)
  def *(other: CharExpression): LongExpression = LongExpression(value * other.value)
  def *(other: ShortExpression): LongExpression = LongExpression(value * other.value)
  def *(other: ByteExpression): LongExpression = LongExpression(value * other.value)
  def +(other: DoubleExpression): DoubleExpression = DoubleExpression(value + other.value)
  def +(other: FloatExpression): FloatExpression = FloatExpression(value + other.value)
  def +(other: LongExpression): LongExpression = LongExpression(value + other.value)
  def +(other: IntExpression): LongExpression = LongExpression(value + other.value)
  def +(other: CharExpression): LongExpression = LongExpression(value + other.value)
  def +(other: ShortExpression): LongExpression = LongExpression(value + other.value)
  def +(other: ByteExpression): LongExpression = LongExpression(value + other.value)
  def +(other: StringExpression): StringExpression = StringExpression(value + other.value)
  def -(other: DoubleExpression): DoubleExpression = DoubleExpression(value - other.value)
  def -(other: FloatExpression): FloatExpression = FloatExpression(value - other.value)
  def -(other: LongExpression): LongExpression = LongExpression(value - other.value)
  def -(other: IntExpression): LongExpression = LongExpression(value - other.value)
  def -(other: CharExpression): LongExpression = LongExpression(value - other.value)
  def -(other: ShortExpression): LongExpression = LongExpression(value - other.value)
  def -(other: ByteExpression): LongExpression = LongExpression(value - other.value)
  def /(other: DoubleExpression): DoubleExpression = DoubleExpression(value / other.value)
  def /(other: FloatExpression): FloatExpression = FloatExpression(value / other.value)
  def /(other: LongExpression): LongExpression = LongExpression(value / other.value)
  def /(other: IntExpression): LongExpression = LongExpression(value / other.value)
  def /(other: CharExpression): LongExpression = LongExpression(value / other.value)
  def /(other: ShortExpression): LongExpression = LongExpression(value / other.value)
  def /(other: ByteExpression): LongExpression = LongExpression(value / other.value)
  def <(other: DoubleExpression): BooleanExpression = BooleanExpression(value < other.value)
  def <(other: FloatExpression): BooleanExpression = BooleanExpression(value < other.value)
  def <(other: LongExpression): BooleanExpression = BooleanExpression(value < other.value)
  def <(other: IntExpression): BooleanExpression = BooleanExpression(value < other.value)
  def <(other: CharExpression): BooleanExpression = BooleanExpression(value < other.value)
  def <(other: ShortExpression): BooleanExpression = BooleanExpression(value < other.value)
  def <(other: ByteExpression): BooleanExpression = BooleanExpression(value < other.value)
  def <<(other: LongExpression): LongExpression = LongExpression(value << other.value)
  def <<(other: IntExpression): LongExpression = LongExpression(value << other.value)
  def <=(other: DoubleExpression): BooleanExpression = BooleanExpression(value <= other.value)
  def <=(other: FloatExpression): BooleanExpression = BooleanExpression(value <= other.value)
  def <=(other: LongExpression): BooleanExpression = BooleanExpression(value <= other.value)
  def <=(other: IntExpression): BooleanExpression = BooleanExpression(value <= other.value)
  def <=(other: CharExpression): BooleanExpression = BooleanExpression(value <= other.value)
  def <=(other: ShortExpression): BooleanExpression = BooleanExpression(value <= other.value)
  def <=(other: ByteExpression): BooleanExpression = BooleanExpression(value <= other.value)
  def ==(other: DoubleExpression): BooleanExpression = BooleanExpression(value == other.value)
  def ==(other: FloatExpression): BooleanExpression = BooleanExpression(value == other.value)
  def ==(other: LongExpression): BooleanExpression = BooleanExpression(value == other.value)
  def ==(other: IntExpression): BooleanExpression = BooleanExpression(value == other.value)
  def ==(other: CharExpression): BooleanExpression = BooleanExpression(value == other.value)
  def ==(other: ShortExpression): BooleanExpression = BooleanExpression(value == other.value)
  def ==(other: ByteExpression): BooleanExpression = BooleanExpression(value == other.value)
  def >(other: DoubleExpression): BooleanExpression = BooleanExpression(value > other.value)
  def >(other: FloatExpression): BooleanExpression = BooleanExpression(value > other.value)
  def >(other: LongExpression): BooleanExpression = BooleanExpression(value > other.value)
  def >(other: IntExpression): BooleanExpression = BooleanExpression(value > other.value)
  def >(other: CharExpression): BooleanExpression = BooleanExpression(value > other.value)
  def >(other: ShortExpression): BooleanExpression = BooleanExpression(value > other.value)
  def >(other: ByteExpression): BooleanExpression = BooleanExpression(value > other.value)
  def >=(other: DoubleExpression): BooleanExpression = BooleanExpression(value >= other.value)
  def >=(other: FloatExpression): BooleanExpression = BooleanExpression(value >= other.value)
  def >=(other: LongExpression): BooleanExpression = BooleanExpression(value >= other.value)
  def >=(other: IntExpression): BooleanExpression = BooleanExpression(value >= other.value)
  def >=(other: CharExpression): BooleanExpression = BooleanExpression(value >= other.value)
  def >=(other: ShortExpression): BooleanExpression = BooleanExpression(value >= other.value)
  def >=(other: ByteExpression): BooleanExpression = BooleanExpression(value >= other.value)
  def >>(other: LongExpression): LongExpression = LongExpression(value >> other.value)
  def >>(other: IntExpression): LongExpression = LongExpression(value >> other.value)
  def >>>(other: LongExpression): LongExpression = LongExpression(value >>> other.value)
  def >>>(other: IntExpression): LongExpression = LongExpression(value >>> other.value)
  def ^(other: LongExpression): LongExpression = LongExpression(value ^ other.value)
  def ^(other: IntExpression): LongExpression = LongExpression(value ^ other.value)
  def ^(other: CharExpression): LongExpression = LongExpression(value ^ other.value)
  def ^(other: ShortExpression): LongExpression = LongExpression(value ^ other.value)
  def ^(other: ByteExpression): LongExpression = LongExpression(value ^ other.value)
  def toByte: ByteExpression = ByteExpression(value.toByte)
  def toChar: CharExpression = CharExpression(value.toChar)
  def toDouble: DoubleExpression = DoubleExpression(value.toDouble)
  def toFloat: FloatExpression = FloatExpression(value.toFloat)
  def toInt: IntExpression = IntExpression(value.toInt)
  def toLong: LongExpression = LongExpression(value.toLong)
  def toShort: ShortExpression = ShortExpression(value.toShort)
  def unary_+: = LongExpression(+value)
  def unary_-: = LongExpression(-value)
  def unary_~: = LongExpression(~value)
  def |(other: LongExpression): LongExpression = LongExpression(value | other.value)
  def |(other: IntExpression): LongExpression = LongExpression(value | other.value)
  def |(other: CharExpression): LongExpression = LongExpression(value | other.value)
  def |(other: ShortExpression): LongExpression = LongExpression(value | other.value)
  def |(other: ByteExpression): LongExpression = LongExpression(value | other.value)
  def abs: LongExpression = LongExpression(value.abs)
  def compare(other: LongExpression): IntExpression = IntExpression(value compare other.value)
  def compareTo(other: LongExpression): IntExpression = IntExpression(value compareTo other.value)
  def isValidByte: BooleanExpression = BooleanExpression(value.isValidByte)
  def isValidChar: BooleanExpression = BooleanExpression(value.isValidChar)
  def isValidInt: BooleanExpression = BooleanExpression(value.isValidInt)
  def isValidLong: BooleanExpression = BooleanExpression(value.isValidLong)
  def isValidShort: BooleanExpression = BooleanExpression(value.isValidShort)
  def isWhole(): BooleanExpression = BooleanExpression(value isWhole)
  def max(other: LongExpression): LongExpression = LongExpression(value max other.value)
  def min(other: LongExpression): LongExpression = LongExpression(value min other.value)
  def signum: IntExpression = IntExpression(value.signum)
  def toBinaryString: StringExpression = StringExpression(value.toBinaryString)
  def toHexString: StringExpression = StringExpression(value.toHexString)
  def toOctalString: StringExpression = StringExpression(value.toOctalString)
}
